"""
HTML Builder - Creates semantic HTML for PDF/UA conversion.

Generates accessible HTML with:
- Proper heading hierarchy (<h1>, <h2>)
- Semantic structure (<article>, <section>)
- Alt text for images
- Accessible tables
- Language attributes
- Progressive Disclosure (<details>/<summary>)
- Unicode-safe text handling (keeps umlauts intact)
"""
import re
from typing import List, Dict, Any, Optional, Set
from html import escape as html_escape

from ..config import (
    INCLUDE_SPEAKER_NOTES,
    INCLUDE_VISUAL_DESCRIPTIONS,
    GENERATE_TOC,
    BACKUP_SLIDES_AS_APPENDIX,
    MAX_SUMMARY_SENTENCES,
    ENABLE_LANGUAGE_TAGGING,
    ENABLE_KPI_DETECTION,
)
from ..deduplication.similarity import overlap_ratio
from ..language import apply_language_tags
BULLET_PREFIXES = ("•", "-", "*", "–", "—", ">")
NUMBER_ONLY_RE = re.compile(r"^\s*\d{1,3}[.)]?\s*$")
NUMBERED_ITEM_RE = re.compile(r"^\s*\d{1,3}[.)]\s+")
VISUAL_KEYWORDS = ("diagramm", "grafik", "foto", "screenshot", "tabelle", "zeitleiste", "fluss", "organigramm", "schema", "icon", "abbildung")
KPI_VALUE_RE = re.compile(r"(?P<value>(?:\d{1,3}(?:[.\s]\d{3})+|\d+)(?:\s*(?:%|Prozent|Mio|Millionen|Tsd|Tausend|Mrd))?)")
KPI_PREFIX_RE = re.compile(r"^(über|rund|ca\.?|circa|etwa|mehr als|mindestens|max\.?)\s+", re.IGNORECASE)
YEAR_RANGE_RE = re.compile(r"\b(?:19|20)\d{2}(?:\s*[–-]\s*(?:\d{2,4}))?\b")


def normalize_lang(lang: Optional[str]) -> str:
    """Normalize language tag to IETF format for PDF/UA."""
    if not lang:
        return "de-DE"
    value = str(lang).replace("_", "-").strip()
    if not value:
        return "de-DE"
    lower = value.lower()
    if "-" not in value:
        if lower == "de":
            return "de-DE"
        if lower == "en":
            return "en-US"
    return value


def convert_umlauts(text: str) -> str:
    """
    Keep umlauts intact. We rely on UTF-8 throughout the pipeline.
    """
    if not text:
        return ""
    return str(text)


def cleanup_llm_artifacts(text: str) -> str:
    """
    Remove technical LLM artifacts from generated text.

    Common artifacts include special tokens, markdown formatting,
    and other model-specific markers that shouldn't appear in output.
    """
    if not text:
        return ""

    # Known LLM markers to remove
    artifacts = [
        "<|end|>",
        "<|im_end|>",
        "<|im_start|>",
        "<|assistant|>",
        "<|user|>",
        "<|system|>",
        "[/INST]",
        "[INST]",
        "<<SYS>>",
        "<</SYS>>",
        "```",
        "---",
        "<end_of_turn>",
        "<start_of_turn>",
    ]

    result = text
    for artifact in artifacts:
        result = result.replace(artifact, "")

    # Remove any remaining angle-bracket tokens like <|...|>
    result = re.sub(r'<\|[^|]+\|>', '', result)

    # Normalize PPTX soft line breaks and whitespace
    result = (
        result.replace("\v", "\n")
        .replace("\x0b", "\n")
        .replace("\x0c", "\n")
        .replace("\u2028", "\n")
        .replace("\u2029", "\n")
    )
    result = re.sub(r'\n{3,}', '\n\n', result)
    result = re.sub(r' {2,}', ' ', result)
    result = _fix_missing_spaces(result)

    return result.strip()


def _fix_missing_spaces(text: str) -> str:
    """Insert missing spaces caused by soft line breaks in PPTX exports."""
    if not text:
        return ""
    value = str(text)
    value = re.sub(r"([.!?:])([A-ZÄÖÜ])", r"\1 \2", value)
    value = re.sub(r"([a-zäöüß]{3,})([A-ZÄÖÜ])", r"\1 \2", value)
    value = re.sub(r"(\d)([A-ZÄÖÜ])", r"\1 \2", value)
    return value


def escape(text: str) -> str:
    """Escape HTML special characters while preserving umlauts."""
    if not text:
        return ""
    return html_escape(convert_umlauts(str(text)))


def format_text(text: str, lang: str) -> str:
    """Escape text and apply language spans when enabled."""
    cleaned = cleanup_llm_artifacts(text)
    if not cleaned:
        return ""
    if ENABLE_LANGUAGE_TAGGING:
        return apply_language_tags(cleaned)
    return escape(cleaned)


def _limit_sentences(text: str, max_sentences: int) -> str:
    if not text:
        return ""
    if max_sentences <= 0:
        return text
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    if len(parts) <= max_sentences:
        return text
    return " ".join(parts[:max_sentences]).strip()


def _get_labels(lang: str) -> Dict[str, str]:
    """Return UI labels based on language."""
    if lang.lower().startswith("en"):
        return {
            "slide": "Slide",
            "summary": "Summary",
            "summary_region": "Slide summary",
            "details_summary": "Show full slide details and raw content",
            "speaker_notes": "Speaker notes",
            "generated_by": "Generated by VoxDrop PDF/UA Service",
            "visual_details": "Image description",
            "key_points": "Key points",
            "steps": "Steps",
            "structured_items": "Structured sections",
            "content": "Content",
            "toc": "Table of Contents",
        }
    return {
        "slide": "Folie",
        "summary": "Zusammenfassung",
        "summary_region": "Zusammenfassung der Folie",
        "details_summary": "Vollständige Foliendetails und Rohdaten anzeigen",
        "speaker_notes": "Sprechernotizen",
        "generated_by": "Generiert von VoxDrop PDF/UA Service",
        "visual_details": "Bildbeschreibung",
        "key_points": "Kernpunkte",
        "steps": "Schritte",
        "structured_items": "Strukturierte Bereiche",
        "content": "Inhalt",
        "toc": "Inhaltsverzeichnis",
    }


def _structured_used_indices(slide: Dict[str, Any]) -> set[int]:
    explicit = slide.get("structured_used_indices")
    if isinstance(explicit, list):
        used: set[int] = set()
        for value in explicit:
            try:
                used.add(int(value))
            except Exception:
                continue
        return used

    used: set[int] = set()
    for item in slide.get("structured_items", []) or []:
        for idx in item.get("source_indices", []) or []:
            try:
                used.add(int(idx))
            except Exception:
                continue
    return used


def _anchor_id(slide_num: int) -> str:
    return f"slide-{slide_num}"


def _build_outline_html(slides: List[Dict[str, Any]], labels: Dict[str, str], lang: str) -> List[str]:
    if not slides:
        return []

    toc_label = labels.get("toc", "Inhaltsverzeichnis")
    parts = [
        f'    <nav class="document-outline" aria-label="{escape(toc_label)}" role="doc-toc">',
        f'      <h2 class="toc-title">{escape(toc_label)}</h2>',
        '      <ol>',
    ]

    for slide in slides:
        slide_num = int(slide.get("slide_number") or 0)
        if slide_num <= 0:
            continue
        title_text = cleanup_llm_artifacts(str(slide.get("title") or "").strip())
        if not title_text:
            title_text = f"{labels['slide']} {slide_num}"
        anchor = _anchor_id(slide_num)
        aria_text = f'{labels["slide"]} {slide_num}: {title_text}'
        # Show a human-friendly TOC entry, but avoid the literal "Folie {n}: ..." prefix
        # to prevent the Java bookmark resolver from matching TOC text instead of the slide page.
        visible_title = cleanup_llm_artifacts(title_text).strip()
        visible_title = re.sub(r"^folie\s*\d+\s*:\s*", "", visible_title, flags=re.IGNORECASE).strip()
        if not visible_title:
            visible_title = "Ohne Titel"
        link_text = f'{slide_num}: {format_text(visible_title, lang)}'
        parts.append(
            # title attribute is a good signal for converters to populate PDF annotation /Contents.
            f'        <li><a href="#{anchor}" aria-label="{escape(aria_text)}" title="{escape(aria_text)}">{link_text}</a></li>'
        )

    parts.extend([
        '      </ol>',
        '    </nav>',
    ])

    return parts


def _ordered_text_blocks(slide: Dict[str, Any]) -> List[Dict[str, Any]]:
    blocks = slide.get("text_ordered") or slide.get("text_content") or []
    if not blocks:
        return []

    if slide.get("text_ordered"):
        return list(blocks)

    if any("top_norm" in b for b in blocks):
        return sorted(
            blocks,
            key=lambda b: (
                float(b.get("top_norm") or 0.0),
                float(b.get("left_norm") or 0.0),
            ),
        )

    return list(blocks)


def _build_structured_items_html(slide: Dict[str, Any], labels: Dict[str, str]) -> tuple[List[str], set[int]]:
    items = slide.get("structured_items") or []
    if not items:
        return [], set()

    used_indices = _structured_used_indices(slide)
    parts: List[str] = [
        f'        <section class="structured-items" aria-label="{escape(labels["structured_items"])}">',
        f'          <h3 class="structured-items-title">{escape(labels["structured_items"])}</h3>',
        '          <ol class="structured-items-list">',
    ]

    for item in items:
        number = str(item.get("number") or "").strip()
        heading = cleanup_llm_artifacts(str(item.get("heading") or "").strip())
        body_parts = [
            cleanup_llm_artifacts(str(text).strip())
            for text in (item.get("body") or [])
            if str(text).strip()
        ]
        body = " ".join(body_parts)

        prefix = f"{number}. " if number else ""
        parts.append('            <li class="structured-item">')
        if heading:
            parts.append(
                f'              <p class="structured-heading"><strong>{escape(prefix + heading)}</strong></p>'
            )
        elif number:
            parts.append(
                f'              <p class="structured-heading"><strong>{escape(prefix)}</strong></p>'
            )

        if body:
            parts.append(f'              <p class="structured-body">{escape(body)}</p>')

        parts.append('            </li>')

    parts.extend([
        '          </ol>',
        '        </section>',
    ])

    return parts, used_indices


def _infer_table_from_blocks(
    blocks: List[Dict[str, Any]],
    skip_indices: Optional[Set[int]] = None,
) -> tuple[List[List[str]], set[int], Dict[str, Any]]:
    """Infer simple tables from aligned text blocks."""
    if not blocks:
        return [], set(), {"accepted": False, "classification_source": "heuristic", "reason": "no_blocks"}
    if not any("top_norm" in b and "left_norm" in b for b in blocks):
        return [], set(), {"accepted": False, "classification_source": "heuristic", "reason": "missing_layout"}
    skip_indices = set(skip_indices or set())

    # Cluster rows by vertical position.
    row_tol = 0.035
    rows: List[Dict[str, Any]] = []
    for block in sorted(blocks, key=lambda b: float(b.get("top_norm") or 0.0)):
        top = float(block.get("top_norm") or 0.0)
        placed = False
        for row in rows:
            if abs(top - row["mean_top"]) <= row_tol:
                row["blocks"].append(block)
                row["mean_top"] = sum(float(b.get("top_norm") or 0.0) for b in row["blocks"]) / max(len(row["blocks"]), 1)
                placed = True
                break
        if not placed:
            rows.append({"mean_top": top, "blocks": [block]})

    if len(rows) < 2:
        return [], set(), {"accepted": False, "classification_source": "heuristic", "reason": "too_few_rows"}

    # Cluster columns by horizontal position.
    col_tol = 0.08
    col_centers: List[float] = []
    for row in rows:
        for block in row["blocks"]:
            left = float(block.get("left_norm") or 0.0)
            placed = False
            for idx, center in enumerate(col_centers):
                if abs(left - center) <= col_tol:
                    col_centers[idx] = (center + left) / 2.0
                    placed = True
                    break
            if not placed:
                col_centers.append(left)

    col_centers = sorted(col_centers)
    if len(col_centers) < 2:
        return [], set(), {"accepted": False, "classification_source": "heuristic", "reason": "single_column"}

    table_rows: List[List[str]] = []
    used_indices: set[int] = set()
    multi_col_rows = 0

    for row in sorted(rows, key=lambda r: r["mean_top"]):
        cells = [""] * len(col_centers)
        for block in sorted(row["blocks"], key=lambda b: float(b.get("left_norm") or 0.0)):
            left = float(block.get("left_norm") or 0.0)
            col_idx = min(range(len(col_centers)), key=lambda i: abs(col_centers[i] - left))
            idx = block.get("index")
            if isinstance(idx, int) and idx in skip_indices:
                continue
            content = str(block.get("content") or "").strip()
            if not content:
                continue
            cells[col_idx] = content
            if isinstance(idx, int):
                used_indices.add(idx)
        if sum(1 for cell in cells if cell.strip()) >= 2:
            multi_col_rows += 1
        table_rows.append(cells)

    if multi_col_rows < 2:
        return [], set(), {"accepted": False, "classification_source": "heuristic", "reason": "no_grid"}

    non_empty_rows = [[cell for cell in row if cell.strip()] for row in table_rows if any(cell.strip() for cell in row)]
    if len(non_empty_rows) < 2:
        return [], set(), {"accepted": False, "classification_source": "heuristic", "reason": "too_few_content_rows"}

    header_cells = non_empty_rows[0]
    header_keywords = ("jahr", "wert", "status", "thema", "rolle", "bereich", "phase", "ziel", "kategorie", "maßnahme")
    has_keyword_header = any(any(keyword in cell.lower() for keyword in header_keywords) for cell in header_cells)
    short_header_cells = sum(1 for cell in header_cells if len(cell) <= 42 and not cell.endswith((".", "?", "!")))
    second_row = non_empty_rows[1]
    numeric_second_row = any(KPI_VALUE_RE.search(cell) for cell in second_row)
    header_evidence = (
        len(non_empty_rows) >= 3
        and len(header_cells) >= 2
        and short_header_cells >= 2
        and (has_keyword_header or numeric_second_row or len(non_empty_rows) >= 4)
    )

    if not header_evidence:
        return [], set(), {"accepted": False, "classification_source": "heuristic", "reason": "missing_header_evidence"}

    return table_rows, used_indices, {"accepted": True, "classification_source": "heuristic", "reason": None}


def _append_risk_flag(slide: Dict[str, Any], flag: str) -> None:
    if not flag:
        return
    risk_flags = slide.setdefault("risk_flags", [])
    if isinstance(risk_flags, list) and flag not in risk_flags:
        risk_flags.append(flag)


def build_html(
    slides: List[Dict[str, Any]],
    document_title: str,
    lang: str = "de",
    output_mode: str = "narrative_summary",
) -> str:
    """
    Build semantic HTML from parsed slides.

    The HTML is structured for OpenHTMLtoPDF to convert to PDF/UA:
    - Each slide becomes a section with page break
    - Headings follow hierarchy (h1 for slide titles)
    - Images have alt text
    - Tables have proper structure
    """
    # Clean document title
    lang = normalize_lang(lang)
    title = escape(document_title.rsplit(".", 1)[0])
    labels = _get_labels(lang)

    html_parts = [
        '<!DOCTYPE html>',
        f'<html lang="{escape(lang)}">',
        '<head>',
        f'  <title>{title}</title>',
        '  <meta charset="UTF-8">',
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '  <style>',
        get_css_styles(),
        '  </style>',
        '</head>',
        '<body>',
        f'  <header role="banner">',
        f'    <h1 class="document-h1" role="doc-title">{title}</h1>',
        f'  </header>',
        '  <main role="main">',
    ]

    if GENERATE_TOC:
        html_parts.extend(_build_outline_html(slides, labels, lang))

    # Process each slide
    appendix_start = _find_appendix_start(slides)
    for idx, slide in enumerate(slides):
        if appendix_start is not None and idx == appendix_start:
            html_parts.extend([
                '    <section class="appendix">',
                '      <h1 class="slide-title appendix-title">Anhang</h1>',
                '      <p>Die folgenden Folien enthalten ergänzende Detailinformationen.</p>',
                '    </section>',
            ])
        # Slide titles remain <h1 class="slide-title"> for bookmark extraction in the Java service.
        is_appendix = appendix_start is not None and idx >= appendix_start
        offset = 0
        slide_html = build_slide_html_v2(
            slide,
            lang,
            slides,
            heading_offset=offset,
            is_appendix=is_appendix,
            output_mode=output_mode,
        )
        html_parts.append(slide_html)

    html_parts.extend([
        '  </main>',
        '</body>',
        '</html>',
    ])

    return '\n'.join(html_parts)


def build_html_v2(
    slides: List[Dict[str, Any]],
    document_title: str,
    lang: str = "de",
    document_summary: Optional[str] = None,
    document_outline: Optional[List[Dict[str, Any]]] = None,
    output_mode: str = "narrative_summary",
) -> str:
    """
    Screenreader-first HTML with document overview + outline.
    Avoids collapsed <details> to keep linear reading predictable.
    """
    lang = normalize_lang(lang)
    title = escape(document_title.rsplit(".", 1)[0])
    labels = _get_labels(lang)

    html_parts = [
        '<!DOCTYPE html>',
        f'<html lang="{escape(lang)}">',
        '<head>',
        f'  <title>{title}</title>',
        '  <meta charset="UTF-8">',
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '  <style>',
        get_css_styles(),
        '  </style>',
        '</head>',
        '<body>',
        f'  <header role="banner">',
        f'    <h1 class="document-h1" role="doc-title">{title}</h1>',
        f'  </header>',
        '  <main role="main">',
    ]

    if output_mode == "narrative_summary":
        summary_text = cleanup_llm_artifacts(document_summary or "").strip()
        if not summary_text:
            summary_text = f"Diese Präsentation enthält {len(slides)} Folien."
        html_parts.extend([
            '    <section class="document-summary" role="region" aria-label="Dokumentübersicht">',
            '      <h2>Überblick</h2>',
            f'      <p>{format_text(summary_text, lang)}</p>',
            '    </section>',
        ])

    if GENERATE_TOC:
        html_parts.extend(_build_outline_html(slides, labels, lang))

    appendix_start = _find_appendix_start(slides)
    for idx, slide in enumerate(slides):
        if appendix_start is not None and idx == appendix_start:
            html_parts.extend([
                '    <section class="appendix">',
                '      <h1 class="slide-title appendix-title">Anhang</h1>',
                '      <p>Die folgenden Folien enthalten ergänzende Detailinformationen.</p>',
                '    </section>',
            ])
        # Slide titles remain <h1 class="slide-title"> for bookmark extraction in the Java service.
        is_appendix = appendix_start is not None and idx >= appendix_start
        offset = 0
        html_parts.append(
            build_slide_html_v2(
                slide,
                lang,
                slides,
                heading_offset=offset,
                is_appendix=is_appendix,
                output_mode=output_mode,
            )
        )

    html_parts.extend([
        '  </main>',
        '</body>',
        '</html>',
    ])

    return '\n'.join(html_parts)


def build_slide_html_v2(
    slide: Dict[str, Any],
    lang: str = "de",
    slides: Optional[List[Dict[str, Any]]] = None,
    heading_offset: int = 0,
    is_appendix: bool = False,
    output_mode: str = "narrative_summary",
) -> str:
    slide_num = int(slide.get("slide_number") or 0)
    lang = normalize_lang(lang)
    labels = _get_labels(lang)
    parts: List[str] = []

    h1 = f"h{1 + heading_offset}"
    h2 = f"h{2 + heading_offset}"
    h3 = f"h{3 + heading_offset}"

    title = slide.get("title") or f"{labels['slide']} {slide_num}"
    title_text = cleanup_llm_artifacts(str(title))
    heading = f'{escape(labels["slide"])} {slide_num}: {format_text(title_text, lang)}'
    if is_appendix:
        heading = f'Anhang – {heading}'
    is_narrative = output_mode == "narrative_summary"

    anchor = _anchor_id(slide_num)
    parts.append(f'    <article class="slide" aria-label="{escape(labels["slide"])} {slide_num}">')
    slide_title_class = "slide-title"
    if is_appendix:
        slide_title_class += " appendix-slide-title"
    parts.append(f'      <{h1} class="{slide_title_class}" id="{anchor}">{heading}</{h1}>')

    summary_text = ""
    if is_narrative:
        slide_summary = slide.get("slide_summary")
        summary_text = cleanup_llm_artifacts(str(slide_summary)) if slide_summary else ""
        if title_text and summary_text.lower().startswith(title_text.lower()):
            summary_text = summary_text[len(title_text):].lstrip(" :.-")
        if not summary_text:
            summary_text = _fallback_summary(slide)
        if not summary_text:
            summary_text = "Keine Inhalte auf dieser Folie."
        summary_text = _limit_sentences(summary_text, MAX_SUMMARY_SENTENCES)
        parts.append(f'      <section class="slide-summary" role="region" aria-label="{escape(labels["summary_region"])}">')
        parts.append(f'        <{h2} class="bookmark-l2">{escape(labels["summary"])}</{h2}>')
        parts.append(f'        <p>{format_text(summary_text, lang)}</p>')
        parts.append('      </section>')

        visual_description = _build_visual_description(slide)
        if visual_description:
            parts.append('      <section class="slide-visual" aria-label="Bildbeschreibung">')
            parts.append(f'        <{h2} class="bookmark-l2">{escape(labels["visual_details"])}</{h2}>')
            parts.append(f'        <p>{format_text(visual_description, lang)}</p>')
            parts.append('      </section>')

    # Content (structured)
    content_parts: List[str] = []
    used_indices: set[int] = set()

    structured_items = slide.get("structured_items") or []
    is_agenda = "agenda" in title_text.lower() or "inhaltsverzeichnis" in title_text.lower()
    if is_agenda and slides and structured_items:
        content_parts.append('        <ol class="agenda-list">')
        for item in structured_items:
            heading_text = str(item.get("heading") or "").strip()
            number = str(item.get("number") or "").strip()
            label = f"{number}. {heading_text}".strip()
            anchor = _match_slide_anchor(heading_text, slides)
            if anchor:
                content_parts.append(
                    f'          <li><a href="#{anchor}">{format_text(label, lang)}</a></li>'
                )
            else:
                content_parts.append(f'          <li>{format_text(label, lang)}</li>')
        content_parts.append('        </ol>')
        for item in structured_items:
            for idx in item.get("source_indices", []) or []:
                if isinstance(idx, int):
                    used_indices.add(idx)
    else:
        for item in structured_items:
            heading_text = str(item.get("heading") or "").strip()
            number = str(item.get("number") or "").strip()
            prefix = f"{number}. " if number else ""
            if heading_text:
                content_parts.append(f'        <{h3}>{format_text(prefix + heading_text, lang)}</{h3}>')
            body = " ".join(str(t).strip() for t in item.get("body") or [] if str(t).strip())
            if body:
                content_parts.append(f'        <p>{format_text(body, lang)}</p>')
            for idx in item.get("source_indices", []) or []:
                if isinstance(idx, int):
                    used_indices.add(idx)

    ordered_blocks = _ordered_text_blocks(slide)
    if ENABLE_KPI_DETECTION:
        kpi_rows, kpi_indices = _extract_kpis(ordered_blocks, used_indices)
        if kpi_rows:
            content_parts.append(f'        <{h3}>Kennzahlen</{h3}>')
            content_parts.append('        <ul class="kpi-list">')
            for label, value in kpi_rows:
                content_parts.append(
                    f'          <li><strong>{format_text(label, lang)}</strong>: {format_text(value, lang)}</li>'
                )
            content_parts.append('        </ul>')
            used_indices.update(kpi_indices)

    summary_points = slide.get("summary_points") or []
    summary_structure = slide.get("summary_structure")
    if is_narrative and summary_points and summary_structure in ("timeline", "process"):
        heading_label = "Zeitleiste" if summary_structure == "timeline" else "Prozessschritte"
        content_parts.append(f'        <{h3}>{escape(heading_label)}</{h3}>')
        content_parts.append('        <ol>')
        for point in summary_points:
            content_parts.append(f'          <li>{format_text(str(point), lang)}</li>')
        content_parts.append('        </ol>')
    elif summary_points and is_narrative:
        # Skip key points if they heavily overlap with the summary (reduces redundancy).
        kp_text = " ".join(str(p).strip() for p in summary_points if str(p).strip())
        kp_overlap = overlap_ratio(summary_text, kp_text) if summary_text and kp_text else 0.0
        if kp_overlap < 0.6:
            content_parts.append(f'        <{h3}>{escape(labels["key_points"])}</{h3}>')
            content_parts.append('        <ul>')
            for point in summary_points:
                txt = str(point).strip()
                if not txt:
                    continue
                content_parts.append(f'          <li>{format_text(txt, lang)}</li>')
            content_parts.append('        </ul>')

    has_explicit_table = any(shape.get("type") == "table" for shape in slide.get("shapes", []) or [])
    inferred_rows, inferred_indices, inferred_meta = ([], set(), {"accepted": False, "classification_source": "heuristic", "reason": "skipped"})
    if not has_explicit_table and not slide.get("is_visual_diagram"):
        inferred_rows, inferred_indices, inferred_meta = _infer_table_from_blocks(ordered_blocks, skip_indices=used_indices)
        if inferred_rows:
            inferred_meta = {
                **inferred_meta,
                "accepted": False,
                "reason": "heuristics_disabled_real_tables_only",
            }
            _append_risk_flag(slide, "pseudo_table")
        elif inferred_meta.get("reason") == "missing_header_evidence":
            _append_risk_flag(slide, "pseudo_table")
        slide["table_inference"] = inferred_meta

    ordered_blocks, merged_skip = _merge_number_fragments(ordered_blocks)
    used_indices.update(merged_skip)
    for text_block in ordered_blocks:
        block_idx = text_block.get("index")
        if isinstance(block_idx, int) and block_idx in used_indices:
            continue
        if text_block.get("_skip_number_fragment"):
            continue
        content = str(text_block.get("content") or "").strip()
        if not content or content == title_text:
            continue
        if _is_editorial_note(content):
            continue
        content = cleanup_llm_artifacts(content)
        paragraphs = [p.strip() for p in content.split("\n") if p.strip()]
        _append_paragraphs_with_lists(content_parts, paragraphs, "        ", lang)

    for img in slide.get("images", []):
        if is_narrative and (img.get("decorative") or img.get("vision_class") == "decorative" or _is_probably_small_icon(img)):
            continue
        image_html = build_image_html(img, slide, slide_num)
        if image_html:
            content_parts.append(image_html)

    for shape in slide.get("shapes", []):
        if shape.get("type") == "table":
            table_summary = f"Tabelle auf Folie {slide_num}"
            content_parts.append(build_table_html({**shape, "summary": table_summary}, lang))
        elif shape.get("type") == "chart":
            content_parts.append(build_chart_html(shape, slide_num, lang))

    if content_parts:
        parts.append('      <section class="slide-content" aria-label="Inhalt">')
        parts.append(f'        <{h2} class="bookmark-l2">{escape(labels["content"])}</{h2}>')
        parts.extend(content_parts)
        parts.append('      </section>')

    # Speaker notes (optional)
    notes_visibility = str(slide.get("speaker_notes_visibility") or "ignored")
    notes = slide.get("speaker_notes") if INCLUDE_SPEAKER_NOTES and notes_visibility == "visible" else None
    if notes:
        notes = cleanup_llm_artifacts(notes)
        parts.append('      <section class="speaker-notes" role="note">')
        parts.append(f'        <{h2} class="bookmark-l2">{escape(labels["speaker_notes"])}</{h2}>')
        parts.append(f'        <p>{format_text(notes, lang)}</p>')
        parts.append('      </section>')

    parts.append('    </article>')

    return '\n'.join(parts)


def build_slide_html(slide: Dict[str, Any], lang: str = "de") -> str:
    """
    Backwards-compatible wrapper for the v2 slide renderer.
    """
    return build_slide_html_v2(slide, lang)


def _looks_generic_alt(text: str) -> bool:
    if not text:
        return True
    lowered = text.strip().lower()
    if lowered in {"abbildung", "grafik", "bild", "image"}:
        return True
    if "abbildung auf folie" in lowered or "bild auf folie" in lowered or "grafik auf folie" in lowered:
        return True
    if "image on slide" in lowered:
        return True
    if len(lowered) < 8:
        return True
    return False


def _is_redundant_alt(text: str, slide: Dict[str, Any]) -> bool:
    if not text:
        return False
    context_parts = []
    for key in ("slide_summary", "structured_text"):
        value = slide.get(key)
        if isinstance(value, str) and value.strip():
            context_parts.append(value.strip())
    context = " ".join(context_parts)
    if not context:
        return False
    overlap = overlap_ratio(text, context)
    return overlap >= 0.6 and not _looks_visual_text(text)


def _slide_context_snippet(slide: Dict[str, Any]) -> str:
    blocks = _ordered_text_blocks(slide)
    for block in blocks:
        content = str(block.get("content") or "").strip()
        if content:
            return cleanup_llm_artifacts(content).replace("\n", " ").strip()
    return ""


def _is_editorial_note(text: str) -> bool:
    lowered = text.strip().lower()
    if not lowered:
        return False
    markers = [
        "falls diese folie gewünscht",
        "redaktionelle notiz",
        "bitte entfernen",
        "nur intern",
    ]
    return any(marker in lowered for marker in markers)


def _fallback_summary(slide: Dict[str, Any]) -> str:
    """Build a short summary when LLM summary is missing."""
    candidates = []
    structured = str(slide.get("structured_text") or "").strip()
    if structured:
        candidates.append(structured)
    blocks = _ordered_text_blocks(slide)
    for block in blocks:
        content = str(block.get("content") or "").strip()
        if content:
            candidates.append(content)
        if len(candidates) >= 2:
            break
    combined = " ".join(candidates)
    combined = re.sub(r"\s+", " ", combined).strip()
    combined = _limit_sentences(combined, MAX_SUMMARY_SENTENCES)
    if combined:
        return combined
    title = str(slide.get("title") or "").strip() or f"Folie {slide.get('slide_number')}"
    return f"Diese Folie behandelt {title}."


def _safe_float(value: Any) -> float:
    try:
        return float(value or 0.0)
    except Exception:
        return 0.0


def _is_probably_small_icon(img: Dict[str, Any]) -> bool:
    area = _safe_float(img.get("area_norm"))
    width = _safe_float(img.get("width_norm"))
    height = _safe_float(img.get("height_norm"))
    if area <= 0.0:
        return False
    return area <= 0.03 and width <= 0.18 and height <= 0.18


def _collect_meaningful_image_descriptions(slide: Dict[str, Any]) -> List[str]:
    descriptions: List[str] = []
    for img in slide.get("images", []) or []:
        if img.get("decorative") or img.get("vision_class") == "decorative":
            continue

        area = _safe_float(img.get("area_norm"))
        width = _safe_float(img.get("width_norm"))
        height = _safe_float(img.get("height_norm"))
        large_enough = area >= 0.08 or (width >= 0.28 and height >= 0.18)
        if not large_enough:
            continue

        candidates = [
            img.get("alt_text"),
            img.get("vision_alt_text"),
            img.get("diagram_description"),
        ]
        chosen = ""
        for candidate in candidates:
            text = cleanup_llm_artifacts(str(candidate or "")).strip()
            if not text or _looks_generic_alt(text) or _is_generic_visual_hint(text):
                continue
            if _is_redundant_alt(text, slide):
                continue
            chosen = text
            break

        if not chosen:
            ocr_text = cleanup_llm_artifacts(str(img.get("vision_ocr_text") or img.get("ocr_text") or "")).strip()
            if len(ocr_text) >= 24:
                if len(ocr_text) > 200:
                    ocr_text = ocr_text[:197] + "..."
                chosen = f"Screenshot mit Text: {ocr_text}"

        if chosen:
            descriptions.append(chosen)

    return descriptions


def _build_visual_description(slide: Dict[str, Any]) -> str:
    """Create a visual description only when it adds real value."""
    if not INCLUDE_VISUAL_DESCRIPTIONS:
        return ""
    has_visual = bool(slide.get("images") or slide.get("has_chart") or slide.get("is_visual_diagram") or slide.get("diagram_summary"))
    if not has_visual:
        return ""

    description = ""
    diagram_summary = str(slide.get("diagram_summary") or "").strip()
    if diagram_summary and _looks_visual_text(diagram_summary):
        description = diagram_summary

    if not description:
        chart_summaries = []
        for shape in slide.get("shapes", []) or []:
            if shape.get("type") == "chart":
                summary = str(shape.get("summary") or "").strip()
                if summary:
                    chart_summaries.append(summary)
        if chart_summaries:
            description = " ".join(chart_summaries)

    if not description:
        informative_alts = _collect_meaningful_image_descriptions(slide)
        if informative_alts:
            description = " ".join(informative_alts)

    return description


def _extract_kpis(
    blocks: List[Dict[str, Any]],
    used_indices: set[int],
) -> tuple[List[tuple[str, str]], set[int]]:
    if not blocks:
        return [], set()

    rows: List[tuple[str, str]] = []
    used: set[int] = set()
    pending_label: Optional[str] = None

    for block in blocks:
        idx = block.get("index")
        if isinstance(idx, int) and idx in used_indices:
            continue
        content = cleanup_llm_artifacts(str(block.get("content") or "")).strip()
        if not content:
            continue
        lines = [line.strip() for line in content.split("\n") if line.strip()]
        for line in lines:
            if len(line) > 140:
                continue
            match = KPI_VALUE_RE.search(line)
            if not match:
                if len(line) <= 80:
                    pending_label = line
                continue
            value = match.group("value").strip()
            label = line.replace(match.group("value"), "").strip(" :–-")
            label = KPI_PREFIX_RE.sub("", label).strip(" :–-")
            if not label and pending_label:
                label = pending_label
            if not label:
                continue
            if YEAR_RANGE_RE.fullmatch(value) and len(label) <= 4:
                continue
            rows.append((label, value))
            if isinstance(idx, int):
                used.add(idx)
            pending_label = None

    deduped: List[tuple[str, str]] = []
    seen: set[str] = set()
    for label, value in rows:
        key = label.lower()
        if key in seen:
            continue
        seen.add(key)
        deduped.append((label, value))

    if len(deduped) < 2:
        return [], set()
    return deduped, used


def _timeline_rows(points: List[str]) -> List[tuple[str, str]]:
    rows: List[tuple[str, str]] = []
    for point in points:
        text = cleanup_llm_artifacts(str(point)).strip()
        if not text:
            continue
        match = YEAR_RANGE_RE.search(text)
        if not match:
            continue
        period = match.group(0).strip()
        description = text.replace(match.group(0), "").strip(" :–-")
        if not description:
            description = text
        rows.append((period, description))
    if len(rows) < 2:
        return []
    return rows


def _append_paragraphs_with_lists(parts: List[str], paragraphs: List[str], indent: str, lang: str) -> None:
    list_items: List[str] = []
    list_type: Optional[str] = None

    def _flush() -> None:
        nonlocal list_items, list_type
        if not list_items:
            return
        tag = "ol" if list_type == "ol" else "ul"
        parts.append(f"{indent}<{tag}>")
        for item in list_items:
            parts.append(f"{indent}  <li>{format_text(item, lang)}</li>")
        parts.append(f"{indent}</{tag}>")
        list_items = []
        list_type = None
    for para in paragraphs:
        if not para:
            continue
        if NUMBER_ONLY_RE.match(para.strip()):
            continue
        if NUMBERED_ITEM_RE.match(para):
            item = NUMBERED_ITEM_RE.sub("", para).strip()
            if list_type and list_type != "ol":
                _flush()
            list_type = "ol"
            list_items.append(item)
            continue
        if para.startswith(BULLET_PREFIXES):
            item = para.lstrip("".join(BULLET_PREFIXES)).strip()
            if list_type and list_type != "ul":
                _flush()
            list_type = "ul"
            list_items.append(item)
            continue
        if list_items:
            _flush()
        parts.append(f"{indent}<p>{format_text(para, lang)}</p>")
    if list_items:
        _flush()


def _normalize_title(title: str) -> str:
    text = re.sub(r"^folie\s*\d+\s*:\s*", "", str(title or ""), flags=re.IGNORECASE).strip()
    text = re.sub(r"\s+", " ", text).lower()
    return text


def _find_appendix_start(slides: List[Dict[str, Any]]) -> Optional[int]:
    if not BACKUP_SLIDES_AS_APPENDIX:
        return None
    keywords = ("fazit", "ausblick", "schluss", "vielen dank", "danke", "fragen")
    for idx, slide in enumerate(slides):
        title = str(slide.get("title") or "").lower()
        if any(key in title for key in keywords):
            if idx + 1 < len(slides):
                return idx + 1
            return None
    return None


def _match_slide_anchor(label: str, slides: List[Dict[str, Any]]) -> Optional[str]:
    if not label:
        return None
    normalized = _normalize_title(label)
    best_anchor = None
    best_score = 0.0
    for slide in slides:
        title = str(slide.get("title") or "").strip()
        if not title:
            continue
        slide_norm = _normalize_title(title)
        score = 0.0
        if normalized and normalized in slide_norm:
            score = 1.0
        else:
            score = overlap_ratio(normalized, slide_norm)
        if score > best_score:
            best_score = score
            best_anchor = _anchor_id(int(slide.get("slide_number") or 0))
    if best_score >= 0.45:
        return best_anchor
    return None


def _resolve_alt_text(img: Dict[str, Any], slide: Dict[str, Any], slide_num: int) -> tuple[str, bool]:
    # Decorative handling
    if img.get("decorative") or img.get("vision_class") == "decorative":
        return "", True
    if _is_probably_small_icon(img):
        ocr_text = str(img.get("vision_ocr_text") or img.get("ocr_text") or "").strip()
        alt_hint = str(img.get("alt_text") or img.get("vision_alt_text") or img.get("existing_alt_text") or "").strip()
        if not ocr_text and (not alt_hint or _looks_generic_alt(alt_hint)):
            return "", True

    candidates = [
        img.get("alt_text"),
        img.get("vision_alt_text"),
        img.get("diagram_description"),
        img.get("existing_alt_text"),
    ]
    for candidate in candidates:
        if candidate is None:
            continue
        text = str(candidate).strip()
        if not text:
            continue
        if _looks_generic_alt(text):
            continue
        if _is_redundant_alt(text, slide):
            continue
        if not _looks_visual_text(text) and (slide.get("has_chart") or slide.get("is_visual_diagram")):
            # Prefer visual descriptions for charts/diagrams.
            continue
        if not _looks_generic_alt(text):
            return text, False

    # Screenshots: prefer OCR context if available.
    ocr_text = str(img.get("vision_ocr_text") or img.get("ocr_text") or "").strip()
    if ocr_text:
        ocr_text = cleanup_llm_artifacts(ocr_text)
        if len(ocr_text) > 200:
            ocr_text = ocr_text[:197] + "..."
        return f"Screenshot mit Text: {ocr_text}", False

    # Build a short fallback from slide title (PDF/UA requires /Alt on figures).
    title = str(slide.get("title") or "").strip()
    if not title:
        title = f"Folie {slide_num}"
    alt = f"Grafik auf Folie {slide_num}: {title}"
    if len(alt) > 200:
        alt = alt[:197] + "..."
    return alt, False


def _is_generic_visual_hint(text: str) -> bool:
    lowered = text.strip().lower()
    if not lowered:
        return True
    generic_patterns = (
        "enthält: diagramm",
        "enthält: grafik",
        "enthält: tabelle",
        "enthält: infografik",
        "contains: diagram",
        "contains: table",
    )
    return any(pattern in lowered for pattern in generic_patterns)


def _looks_visual_text(text: str) -> bool:
    lowered = text.lower()
    return any(keyword in lowered for keyword in VISUAL_KEYWORDS)


def _merge_number_fragments(blocks: List[Dict[str, Any]]) -> tuple[List[Dict[str, Any]], set[int]]:
    """
    Merge isolated numeric fragments (e.g., "1.", "2.") into the nearest text block.
    Returns updated blocks and a set of indices to skip.
    """
    if not blocks:
        return blocks, set()

    skip_indices: set[int] = set()

    for i, block in enumerate(blocks):
        content = str(block.get("content") or "").strip()
        if not content or not NUMBER_ONLY_RE.match(content):
            continue

        top = float(block.get("top_norm") or 0.0)
        left = float(block.get("left_norm") or 0.0)
        best = None
        best_dist = 1e9

        for j, candidate in enumerate(blocks):
            if j == i:
                continue
            cand_text = str(candidate.get("content") or "").strip()
            if not cand_text:
                continue
            cand_top = float(candidate.get("top_norm") or 0.0)
            cand_left = float(candidate.get("left_norm") or 0.0)
            # Same row and to the right
            if abs(cand_top - top) > 0.04:
                continue
            if cand_left <= left:
                continue
            dist = (cand_left - left) + abs(cand_top - top)
            if dist < best_dist:
                best_dist = dist
                best = candidate

        if best:
            prefix = content.strip()
            cand_text = str(best.get("content") or "")
            if not cand_text.strip().startswith(prefix):
                best["content"] = f"{prefix} {cand_text}".strip()
            idx = block.get("index")
            if isinstance(idx, int):
                skip_indices.add(idx)
            block["_skip_number_fragment"] = True

    return blocks, skip_indices


def build_image_html(img: Dict[str, Any], slide: Dict[str, Any], slide_num: int) -> str:
    """Build HTML for an image with alt text."""
    alt_text, decorative = _resolve_alt_text(img, slide, slide_num)
    if not alt_text and not decorative:
        title = str(slide.get("title") or "").strip() or f"Folie {slide_num}"
        alt_text = f"Grafik auf Folie {slide_num}: {title}"

    # Cleanup LLM artifacts and escape for HTML attribute
    alt_text = cleanup_llm_artifacts(alt_text or "")
    alt_text = escape(alt_text)

    # Get data URI for embedding
    data_uri = img.get("data_uri", "")

    # Calculate reasonable display size (max 600px width)
    width = img.get("width_inches", 0) * 96  # Convert to pixels
    if width > 600:
        width = 600

    height = img.get("height_inches", 0) * 96
    # Keep a visible box even when PPTX metadata is missing.
    if height <= 0:
        height = max(120, min(360, width * 0.6 if width else 180))

    if decorative:
        # World-class PDF/UA: decorative visuals should not appear as /Figure at all.
        # Rendering as CSS background keeps the visual output but avoids an <img> tag
        # that would create a Figure in the structure tree.
        return f'''      <div class="image-block decorative-image" role="presentation" aria-hidden="true"
        style="width: {int(width)}px; height: {int(height)}px; background-image: url('{data_uri}'); background-repeat: no-repeat; background-position: center; background-size: contain;">
      </div>'''

    return f'''      <div class="image-block">
        <img src="{data_uri}" alt="{alt_text}" style="max-width: {width}px; height: auto;">
      </div>'''


def build_table_html(table_data: Dict[str, Any], lang: str = "de") -> str:
    """Build accessible HTML table with merged-cell and column-width support.

    Cells may be plain strings (legacy) **or** dicts with keys
    ``text``, ``colspan``, ``rowspan``.  Both formats are handled
    transparently so existing callers keep working.
    """
    rows = table_data.get("rows", [])
    if not rows:
        return ""

    def _cell_text(cell) -> str:
        """Return display text regardless of cell format."""
        if isinstance(cell, dict):
            return cell.get("text", "")
        return cell if str(cell).strip() else ""

    def _cell_span(cell, attr: str) -> int:
        if isinstance(cell, dict):
            return int(cell.get(attr, 1))
        return 1

    def _span_attrs(cell) -> str:
        """Return colspan/rowspan HTML attributes when > 1."""
        parts = []
        cs = _cell_span(cell, "colspan")
        rs = _cell_span(cell, "rowspan")
        if cs > 1:
            parts.append(f' colspan="{cs}"')
        if rs > 1:
            parts.append(f' rowspan="{rs}"')
        return "".join(parts)

    summary = str(table_data.get("summary") or "").strip()
    summary_attr = f' summary="{escape(summary)}"' if summary else ""
    parts = [f'      <table{summary_attr}>']

    # Optional <colgroup> with relative widths
    col_widths = table_data.get("col_widths") or []
    if col_widths:
        parts.append('        <colgroup>')
        for w in col_widths:
            pct = round(w * 100, 1)
            parts.append(f'          <col style="width: {pct}%">')
        parts.append('        </colgroup>')

    # First row as header
    if rows:
        parts.append('        <thead>')
        parts.append('          <tr>')
        for cell in rows[0]:
            text = _cell_text(cell)
            spans = _span_attrs(cell)
            parts.append(f'            <th scope="col"{spans}>{format_text(text, lang)}</th>')
        parts.append('          </tr>')
        parts.append('        </thead>')

    # Remaining rows as body
    if len(rows) > 1:
        parts.append('        <tbody>')
        for row in rows[1:]:
            parts.append('          <tr>')
            for i, cell in enumerate(row):
                text = _cell_text(cell)
                spans = _span_attrs(cell)
                if i == 0:
                    parts.append(f'            <th scope="row"{spans}>{format_text(text, lang)}</th>')
                else:
                    parts.append(f'            <td{spans}>{format_text(text, lang)}</td>')
            parts.append('          </tr>')
        parts.append('        </tbody>')

    parts.append('      </table>')

    return '\n'.join(parts)


def build_chart_html(chart_data: Dict[str, Any], slide_num: int, lang: str = "de") -> str:
    """Build accessible HTML for a chart. Render as text (not <figure>) to avoid /Figure without /Alt."""
    chart_type_german = cleanup_llm_artifacts(chart_data.get("chart_type_german", "Diagramm"))
    chart_title = cleanup_llm_artifacts(chart_data.get("title", ""))
    summary = cleanup_llm_artifacts(chart_data.get("summary", ""))

    # Build description
    parts = []

    # Main title/type
    if chart_title:
        parts.append(f"{chart_type_german}: {chart_title}")
    else:
        parts.append(chart_type_german)

    # Use VLM summary if available
    if summary:
        parts.append(summary)
    else:
        # Generate description from data
        data_description = generate_chart_data_description(chart_data)
        if data_description:
            parts.append(data_description)

    description = " ".join(parts)

    caption_text = summary or generate_chart_data_description(chart_data) or "Diagramm mit Datenvisualisierung"
    title_html = f'<p class="chart-title">{format_text(chart_title, lang)}</p>' if chart_title else ''
    return f'''      <section class="chart" aria-label="{escape(description)}">
        <p class="chart-kind"><strong>{format_text(chart_type_german, lang)}</strong></p>
        {title_html}
        <p class="chart-summary">{format_text(caption_text, lang)}</p>
      </section>'''


def generate_chart_data_description(chart_data: Dict[str, Any]) -> str:
    """Generate a text description from chart data."""
    parts = []

    series_data = chart_data.get("series_data", [])
    categories = chart_data.get("categories", [])
    chart_type = chart_data.get("chart_type", "")

    # Describe categories if available
    if categories:
        if len(categories) <= 5:
            parts.append(f"Kategorien: {', '.join(str(c) for c in categories)}.")
        else:
            parts.append(f"{len(categories)} Kategorien von {categories[0]} bis {categories[-1]}.")

    # Describe series
    if series_data:
        for series in series_data[:3]:  # Limit to 3 series
            series_name = series.get("name")
            values = series.get("values", [])

            if series_name and values:
                # Calculate stats
                try:
                    numeric_values = [v for v in values if isinstance(v, (int, float))]
                    if numeric_values:
                        min_val = min(numeric_values)
                        max_val = max(numeric_values)

                        if "PIE" in chart_type or "DOUGHNUT" in chart_type:
                            # For pie charts, list percentages
                            total = sum(numeric_values)
                            if total > 0:
                                percentages = [(v / total * 100) for v in numeric_values[:5]]
                                parts.append(f"{series_name}: Werte von {min_val:.0f} bis {max_val:.0f}.")
                        else:
                            parts.append(f"{series_name}: Werte von {min_val:.0f} bis {max_val:.0f}.")
                except Exception:
                    pass

    return " ".join(parts) if parts else ""


def build_chart_placeholder(chart_data: Dict[str, Any], slide_num: int, lang: str = "de") -> str:
    """Build placeholder for chart (legacy fallback)."""
    return build_chart_html(chart_data, slide_num, lang)


def get_css_styles() -> str:
    """Get CSS styles for the document."""
    return '''
    @page {
      size: A4;
      margin: 2cm;
    }

    body {
      font-family: "DejaVu Sans", Arial, Helvetica, sans-serif;
      font-size: 12pt;
      line-height: 1.5;
      color: #000;
      background: #fff;
    }

    .document-title,
    .document-h1 {
      font-size: 24pt;
      margin-bottom: 1cm;
      text-align: center;
      -fs-bookmark-level: 1;
      -fs-bookmark-state: open;
    }

    .document-summary,
    .document-outline {
      margin-bottom: 0.6cm;
      padding: 0.4cm;
      border: 1px solid #ddd;
      background: #fafafa;
    }

    .document-outline ol {
      margin: 0.3cm 0 0 0.6cm;
      padding: 0;
    }

    .document-outline a {
      color: #000;
      text-decoration: underline;
    }

    .slide {
      page-break-before: always;
      page-break-after: always;
      margin-bottom: 1cm;
    }

    .slide:last-child {
      page-break-after: avoid;
    }

    .slide-title {
      font-size: 18pt;
      margin-bottom: 0.5cm;
      border-bottom: 2px solid #333;
      padding-bottom: 0.25cm;
      -fs-bookmark-level: 2;
      -fs-bookmark-state: open;
      font-family: "DejaVu Sans Bold", "DejaVu Sans", sans-serif;
    }

    .appendix {
      page-break-before: always;
      margin: 0 0 0.8cm 0;
    }

    .appendix-title {
      font-size: 18pt;
      margin: 0.2cm 0 0.2cm 0;
      -fs-bookmark-level: 2;
      -fs-bookmark-state: open;
      font-family: "DejaVu Sans Bold", "DejaVu Sans", sans-serif;
    }

    .appendix-slide-title {
      -fs-bookmark-level: 3;
      -fs-bookmark-state: open;
    }

    h1, h2, h3, h4, strong {
      font-family: "DejaVu Sans Bold", "DejaVu Sans", sans-serif;
    }

    p {
      margin: 0.3cm 0;
    }

    .bullet {
      margin-left: 1cm;
    }

    figure,
    .image-block {
      margin: 0.5cm 0;
      text-align: center;
    }

    img {
      max-width: 100%;
      height: auto;
    }

    table {
      border-collapse: collapse;
      width: 100%;
      margin: 0.5cm 0;
    }

    th, td {
      border: 1px solid #333;
      padding: 0.25cm;
      text-align: left;
    }

    th {
      background-color: #f0f0f0;
      font-weight: bold;
    }

    .speaker-notes {
      margin-top: 0.5cm;
      padding: 0.25cm;
      background-color: #f9f9f9;
      border-left: 3px solid #ccc;
      font-size: 10pt;
    }

    .chart-description {
      margin-bottom: 0.2cm;
      font-size: 11pt;
    }

    .chart-kind {
      margin: 0.1cm 0;
    }

    .chart-title {
      font-style: italic;
      margin-bottom: 0.2cm;
    }

    .chart-summary {
      font-size: 10pt;
      color: #333;
      line-height: 1.4;
    }

    .diagram-description,
    .slide-summary {
      background-color: #f5f5f5;
      border-left: 3px solid #4a90d9;
      padding: 0.3cm;
      font-size: 10pt;
      color: #333;
      line-height: 1.4;
      margin: 0.3cm 0;
    }

    .slide-content {
      margin-top: 0.3cm;
    }

    .slide-summary .visual-hint {
      background: #e3f2fd;
      border-left: 3px solid #2196f3;
      padding: 0.2cm 0.3cm;
      margin: 0.2cm 0;
      font-style: italic;
      color: #1565c0;
      font-size: 9.5pt;
    }

    .slide-summary .summary-points {
      margin: 0.2cm 0 0.1cm 0.4cm;
      padding: 0;
      font-size: 10pt;
    }

    .slide-summary .summary-points-title {
      margin: 0.2cm 0 0.1cm 0;
      font-size: 10pt;
    }

    .slide-summary .summary-points li {
      margin: 0.1cm 0;
    }

    .slide-summary .visual-details {
      margin-top: 0.2cm;
      font-size: 9.5pt;
      color: #444;
    }

    /* Progressive Disclosure */
    .slide-details {
      margin-top: 0.5cm;
      border: 1px solid #ccc;
    }

    .slide-details summary {
      padding: 0.3cm;
      background-color: #f0f0f0;
      cursor: pointer;
      font-weight: 500;
    }

    .slide-details summary:hover {
      background-color: #e0e0e0;
    }

    .slide-details-content {
      padding: 0.3cm;
    }

    .structured-items {
      margin: 0.2cm 0 0.4cm 0;
      padding: 0.2cm 0.3cm;
      border: 1px solid #e0e0e0;
      background: #fafafa;
    }

    .structured-items-title {
      font-size: 11pt;
      margin: 0 0 0.2cm 0;
    }

    .structured-items-list {
      margin: 0.1cm 0 0.1cm 0.5cm;
      padding: 0;
    }

    .structured-item {
      margin: 0.15cm 0;
    }

    .structured-heading {
      margin: 0;
    }

    .structured-body {
      margin: 0.05cm 0 0.1cm 0;
    }

    .speaker-notes h4 {
      margin: 0 0 0.2cm 0;
      font-size: 10pt;
    }

    footer {
      margin-top: 1cm;
      font-size: 9pt;
      color: #666;
      text-align: center;
    }
    '''
