"""
Podcast Service - Converts PPTX presentations to audio podcasts
Uses Piper TTS for speech synthesis and Ollama for script generation
"""
import os
import uuid
import asyncio
from typing import Dict, Any, Optional, List
import json
import time
from datetime import datetime

from fastapi import FastAPI, UploadFile, File, HTTPException, BackgroundTasks, Query, Body
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.config import OLLAMA_CONFIG, PIPER_CONFIG, UPLOAD_DIR, OUTPUT_DIR, VLM_CONFIG
from app.parsers.pptx_parser import extract_slide_content, extract_slides_with_descriptions, get_presentation_metadata
from app.pipeline.pipeline import run_pptx_to_podcast_pipeline
from app.generators.tts_generator import generate_podcast_audio, list_available_voices, get_tts_status
from app.voiceover import generate_voiceover, extract_text_from_docx


app = FastAPI(
    title="Podcast Service",
    description="Convert PPTX presentations to audio podcasts",
    version="1.0.0"
)

cors_origins_env = os.getenv("CORS_ORIGINS", "")
cors_origins = [origin.strip() for origin in cors_origins_env.split(",") if origin.strip()]
if "*" in cors_origins:
    cors_origins = ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Create directories
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# In-memory job storage
jobs: Dict[str, Dict[str, Any]] = {}
PODCAST_DISFLUENCIES = os.getenv("PODCAST_DISFLUENCIES", "false").lower() == "true"

TTS_PRESET_INSTRUCTS: Dict[str, str] = {
    "klar": "Sprich ruhig, klar und praezise in Hochdeutsch mit gleichmaessigem Tempo.",
    "lebendig": "Sprich lebendig, natuerlich und warm in Hochdeutsch mit sinnvollen Pausen.",
    "dynamisch": "Sprich dynamisch und energiegeladen in Hochdeutsch mit variierter Betonung.",
}


def resolve_tts_instruct(tts_preset: Optional[str]) -> Optional[str]:
    if not tts_preset:
        return None
    return TTS_PRESET_INSTRUCTS.get(tts_preset)


class ConvertResponse(BaseModel):
    job_id: str
    status: str
    message: str


class JobStatus(BaseModel):
    job_id: str
    status: str
    progress: int
    current_stage: str
    created_at: str
    completed_at: Optional[str] = None
    duration_seconds: Optional[float] = None
    error: Optional[str] = None


class ConvertPackRequest(BaseModel):
    """
    Summary pack generated by pdfua-service's /podcast-pack endpoint.
    pronunciationRules is kept as a JSON string for compatibility with the existing UI.
    """

    pack: Dict[str, Any]
    pronunciationRules: Optional[str] = None


async def process_podcast(
    job_id: str,
    file_path: str,
    filename: str,
    style: str,
    speaker_style: str,
    pronunciation_rules: Optional[List[Dict[str, str]]] = None,
    tts_engine: Optional[str] = None,
    tts_preset: Optional[str] = None,
):
    """
    Background task to process PPTX to podcast conversion.

    Enhanced pipeline:
    1. Extract slides + VLM image descriptions (parallel)
    2. Analyze presentation structure
    3. Generate context-aware script
    4. Generate audio (can be parallelized)
    """
    try:
        started_at_perf = time.perf_counter()
        script_started_perf: Optional[float] = None
        tts_started_perf: Optional[float] = None
        jobs[job_id]["pipeline_path"] = "legacy"
        jobs[job_id]["timings"] = {
            "scriptMs": 0,
            "ttsMs": 0,
            "totalMs": 0,
        }

        # Stage 1: Extract slides with VLM image descriptions
        jobs[job_id]["status"] = "extracting"
        jobs[job_id]["current_stage"] = "Folien werden extrahiert..."
        jobs[job_id]["progress"] = 5

        # Use async extraction with VLM if enabled
        if VLM_CONFIG.get("enabled", True):
            jobs[job_id]["current_stage"] = "Bilder werden analysiert..."

            def vlm_progress(percent, stage):
                # Scale VLM progress from 5-20%
                scaled = 5 + int(percent * 0.15)
                jobs[job_id]["progress"] = scaled
                jobs[job_id]["current_stage"] = stage

            slides_data = await extract_slides_with_descriptions(file_path, vlm_progress)
        else:
            slides_data = await asyncio.to_thread(extract_slide_content, file_path)

        if not slides_data:
            raise ValueError("Keine Folien gefunden in der Präsentation")

        # Count images that got descriptions
        total_images = sum(len(s.get("images", [])) for s in slides_data)
        described_images = sum(
            1 for s in slides_data
            for img in s.get("images", [])
            if img.get("description")
        )
        if total_images > 0:
            print(f"[Podcast] {described_images}/{total_images} images described by VLM")

        jobs[job_id]["progress"] = 20

        # Stage 2: High-quality NotebookLM-inspired pipeline (Digest -> Chapters -> Briefs -> Script -> Disfluency)
        jobs[job_id]["status"] = "generating"
        jobs[job_id]["current_stage"] = "Podcast-Skript wird erstellt..."
        jobs[job_id]["progress"] = 20
        script_started_perf = time.perf_counter()

        def script_progress(percent, stage):
            # Scale script progress from 20-55%
            scaled = 20 + int(percent * 0.35)
            jobs[job_id]["progress"] = scaled
            jobs[job_id]["current_stage"] = stage

        def run_pipeline():
            segments, artifacts = run_pptx_to_podcast_pipeline(
                slides_data,
                style=style,
                speaker_style=speaker_style,
                progress_callback=script_progress,
                disfluencies=PODCAST_DISFLUENCIES,
            )
            return segments, artifacts

        script_segments, artifacts = await asyncio.to_thread(run_pipeline)
        # Convert pydantic models to plain dicts for downstream TTS generator.
        try:
            script_segments = [s.model_dump() if hasattr(s, "model_dump") else s for s in script_segments]
        except Exception:
            pass

        if not script_segments:
            raise ValueError("Skript-Generierung fehlgeschlagen")

        if script_started_perf is not None:
            jobs[job_id]["timings"]["scriptMs"] = max(0, int((time.perf_counter() - script_started_perf) * 1000))

        jobs[job_id]["progress"] = 55
        jobs[job_id]["script_segments"] = len(script_segments)
        jobs[job_id]["chapters"] = artifacts.get("plan", {}).get("chapters", []) if isinstance(artifacts.get("plan"), dict) else artifacts.get("plan")
        print(f"[Podcast] Generated {len(script_segments)} script segments")

        # Stage 3: Generate audio
        jobs[job_id]["status"] = "synthesizing"
        jobs[job_id]["current_stage"] = "Audio wird generiert..."
        tts_started_perf = time.perf_counter()

        output_path = os.path.join(OUTPUT_DIR, f"podcast_{job_id}.mp3")

        def progress_callback(percent, stage):
            # Scale progress from 55-95%
            scaled = 55 + int(percent * 0.40)
            jobs[job_id]["progress"] = scaled
            jobs[job_id]["current_stage"] = f"Audio: {stage}"

        result = await asyncio.to_thread(
            generate_podcast_audio,
            segments=script_segments,
            style=style,
            output_path=output_path,
            progress_callback=progress_callback,
            pronunciation_rules=pronunciation_rules,
            tts_engine=tts_engine,
            qwen_instruct=resolve_tts_instruct(tts_preset),
            # Robust-by-default: prefer the selected engine but always allow fallback.
            strict_engine=False,
        )

        if not result.get("success"):
            raise ValueError(result.get("error", "Audio-Generierung fehlgeschlagen"))

        if tts_started_perf is not None:
            jobs[job_id]["timings"]["ttsMs"] = max(0, int((time.perf_counter() - tts_started_perf) * 1000))

        # Stage 4: Finalize
        jobs[job_id]["status"] = "completed"
        jobs[job_id]["current_stage"] = "Fertig"
        jobs[job_id]["progress"] = 100
        jobs[job_id]["completed_at"] = datetime.utcnow().isoformat()
        jobs[job_id]["output_path"] = output_path
        jobs[job_id]["duration_seconds"] = result.get("duration_seconds", 0)
        jobs[job_id]["timings"]["totalMs"] = max(0, int((time.perf_counter() - started_at_perf) * 1000))

        # Cleanup input file
        if os.path.exists(file_path):
            os.remove(file_path)

    except Exception as e:
        jobs[job_id]["status"] = "failed"
        jobs[job_id]["error"] = str(e)
        jobs[job_id]["current_stage"] = "Fehler"
        timings = jobs[job_id].get("timings")
        if isinstance(timings, dict):
            timings["totalMs"] = max(0, int((time.perf_counter() - started_at_perf) * 1000))
        print(f"[Podcast] Job {job_id} failed: {e}")

        # Cleanup
        if os.path.exists(file_path):
            os.remove(file_path)


async def process_podcast_from_pack(
    job_id: str,
    pack: Dict[str, Any],
    style: str,
    speaker_style: str,
    pronunciation_rules_json: Optional[str] = None,
    tts_engine: Optional[str] = None,
    tts_preset: Optional[str] = None,
):
    """
    Background task to process Podcast generation from a precomputed summary pack (no PPTX parsing, no VLM).
    """
    try:
        started_at_perf = time.perf_counter()
        script_started_perf: Optional[float] = None
        tts_started_perf: Optional[float] = None
        jobs[job_id]["pipeline_path"] = "pack"
        jobs[job_id]["timings"] = {
            "scriptMs": 0,
            "ttsMs": 0,
            "totalMs": 0,
        }

        jobs[job_id]["status"] = "generating"
        jobs[job_id]["current_stage"] = "Skript wird erstellt..."
        jobs[job_id]["progress"] = 15
        script_started_perf = time.perf_counter()

        parsed_rules = None
        if pronunciation_rules_json:
            try:
                parsed = json.loads(pronunciation_rules_json)
                if isinstance(parsed, list):
                    parsed_rules = parsed
            except Exception:
                parsed_rules = None

        def script_progress(percent, stage):
            # Scale script progress from 15-55%
            scaled = 15 + int(percent * 0.40)
            jobs[job_id]["progress"] = scaled
            jobs[job_id]["current_stage"] = stage

        def run_pipeline():
            from app.pipeline.pack_pipeline import run_pack_to_podcast_pipeline

            segments, artifacts = run_pack_to_podcast_pipeline(
                pack,
                style=style,
                speaker_style=speaker_style,
                progress_callback=script_progress,
                disfluencies=PODCAST_DISFLUENCIES,
            )
            return segments, artifacts

        script_segments, artifacts = await asyncio.to_thread(run_pipeline)
        try:
            script_segments = [s.model_dump() if hasattr(s, "model_dump") else s for s in script_segments]
        except Exception:
            pass

        if not script_segments:
            raise ValueError("Skript-Generierung fehlgeschlagen")

        if script_started_perf is not None:
            jobs[job_id]["timings"]["scriptMs"] = max(0, int((time.perf_counter() - script_started_perf) * 1000))

        jobs[job_id]["progress"] = 55
        jobs[job_id]["script_segments"] = len(script_segments)

        # Use the pack outline as chapters (lightweight; UI only needs a list).
        chapters = []
        try:
            doc = pack.get("document") if isinstance(pack.get("document"), dict) else {}
            outline = doc.get("outline") if isinstance(doc.get("outline"), list) else []
            chapters = outline
        except Exception:
            chapters = []
        jobs[job_id]["chapters"] = chapters

        # Stage 2: Generate audio
        jobs[job_id]["status"] = "synthesizing"
        jobs[job_id]["current_stage"] = "Audio wird generiert..."
        tts_started_perf = time.perf_counter()

        output_path = os.path.join(OUTPUT_DIR, f"podcast_{job_id}.mp3")

        def audio_progress(percent, stage):
            # Scale progress from 55-95%
            scaled = 55 + int(percent * 0.40)
            jobs[job_id]["progress"] = scaled
            jobs[job_id]["current_stage"] = f"Audio: {stage}"

        # Default to Qwen3-TTS for the new pipeline (batch endpoint is fastest).
        effective_engine = (tts_engine or "qwen3tts").lower()

        result = await asyncio.to_thread(
            generate_podcast_audio,
            segments=script_segments,
            style=style,
            output_path=output_path,
            progress_callback=audio_progress,
            pronunciation_rules=parsed_rules,
            tts_engine=effective_engine,
            qwen_instruct=resolve_tts_instruct(tts_preset),
            strict_engine=False,
        )

        if not result.get("success"):
            raise ValueError(result.get("error", "Audio-Generierung fehlgeschlagen"))

        if tts_started_perf is not None:
            jobs[job_id]["timings"]["ttsMs"] = max(0, int((time.perf_counter() - tts_started_perf) * 1000))

        jobs[job_id]["status"] = "completed"
        jobs[job_id]["current_stage"] = "Fertig"
        jobs[job_id]["progress"] = 100
        jobs[job_id]["completed_at"] = datetime.utcnow().isoformat()
        jobs[job_id]["output_path"] = output_path
        jobs[job_id]["duration_seconds"] = result.get("duration_seconds", 0)
        jobs[job_id]["timings"]["totalMs"] = max(0, int((time.perf_counter() - started_at_perf) * 1000))

    except Exception as e:
        jobs[job_id]["status"] = "failed"
        jobs[job_id]["error"] = str(e)
        jobs[job_id]["current_stage"] = "Fehler"
        timings = jobs[job_id].get("timings")
        if isinstance(timings, dict):
            timings["totalMs"] = max(0, int((time.perf_counter() - started_at_perf) * 1000))
        print(f"[Podcast] Job {job_id} failed (pack): {e}")


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    # Check Ollama connection
    ollama_available = False
    ollama_error = None
    try:
        import ollama
        client = ollama.Client(host=OLLAMA_CONFIG["host"])
        client.list()
        ollama_available = True
    except Exception as e:
        ollama_error = str(e)

    # Check VLM availability
    vlm_available = False
    vlm_error = None
    if VLM_CONFIG.get("enabled", True):
        try:
            from app.processors.vlm_captioner import get_vlm_captioner
            captioner = get_vlm_captioner()
            # The podcast VLM captioner uses the shared vLLM vision server (OpenAI-compatible).
            vlm_available = await captioner.verify_vllm()
        except Exception as e:
            vlm_error = str(e)

    # Get TTS status (includes XTTS and Piper)
    tts_status = get_tts_status()

    return {
        "status": "ok" if ollama_available else "degraded",
        "ollama": {
            "available": ollama_available,
            "host": OLLAMA_CONFIG["host"],
            "model": OLLAMA_CONFIG["model"],
            "error": ollama_error,
        },
        "vlm": {
            "enabled": VLM_CONFIG.get("enabled", True),
            "available": vlm_available,
            "model": VLM_CONFIG.get("model", ""),
            "error": vlm_error,
        },
        "tts": tts_status,
    }


@app.post("/convert", response_model=ConvertResponse)
async def convert_pptx(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    style: str = Query(default="dialog", regex="^(dialog|monolog)$"),
    speakerStyle: str = Query(default="sachlich", regex="^(sachlich|lebendig|lustig|locker)$"),
    pronunciationRules: Optional[str] = None,  # JSON string of pronunciation rules
    ttsEngine: Optional[str] = Query(default=None),
    ttsPreset: str = Query(default="lebendig", regex="^(klar|lebendig|dynamisch)$"),
):
    """
    Convert a PPTX file to a podcast.

    - **file**: PowerPoint file (.pptx or .ppt)
    - **style**: 'dialog' (two speakers) or 'monolog' (one narrator)
    - **speakerStyle**: 'sachlich', 'lebendig', 'lustig', or 'locker'
    - **pronunciationRules**: JSON array of {"original": "...", "spoken": "..."} rules
    - **ttsEngine**: 'xtts', 'qwen3tts', or 'piper'
    - **ttsPreset**: 'klar', 'lebendig' oder 'dynamisch' (Qwen Sprachstil)
    """
    # Validate file type
    if not file.filename:
        raise HTTPException(status_code=400, detail="Dateiname erforderlich")

    ext = file.filename.lower().split(".")[-1]
    if ext not in ["pptx", "ppt"]:
        raise HTTPException(
            status_code=400,
            detail=f"Ungültiger Dateityp: {ext}. Unterstützt: PPTX, PPT"
        )

    # Parse pronunciation rules if provided
    parsed_rules = None
    if pronunciationRules:
        try:
            parsed_rules = json.loads(pronunciationRules)
            if not isinstance(parsed_rules, list):
                parsed_rules = None
        except json.JSONDecodeError:
            parsed_rules = None

    # Validate TTS engine if provided
    valid_engines = {"xtts", "qwen3tts", "piper"}
    if ttsEngine:
        ttsEngine = ttsEngine.lower()
        if ttsEngine not in valid_engines:
            raise HTTPException(status_code=400, detail="Ungueltige TTS-Engine")

    # Create job
    job_id = str(uuid.uuid4())
    file_path = os.path.join(UPLOAD_DIR, f"{job_id}_{file.filename}")

    # Save file
    content = await file.read()
    with open(file_path, "wb") as f:
        f.write(content)

    # Initialize job
    jobs[job_id] = {
        "job_id": job_id,
        "filename": file.filename,
        "style": style,
        "speaker_style": speakerStyle,
        "tts_preset": ttsPreset,
        "pipeline_path": "legacy",
        "status": "pending",
        "progress": 0,
        "current_stage": "In Warteschlange...",
        "created_at": datetime.utcnow().isoformat(),
        "completed_at": None,
        "error": None,
        "output_path": None,
        "duration_seconds": None,
        "timings": {"scriptMs": 0, "ttsMs": 0, "totalMs": 0},
    }

    # Start processing in background
    if ttsEngine:
        jobs[job_id]["tts_engine"] = ttsEngine
        background_tasks.add_task(process_podcast, job_id, file_path, file.filename, style, speakerStyle, parsed_rules, ttsEngine, ttsPreset)
    else:
        background_tasks.add_task(process_podcast, job_id, file_path, file.filename, style, speakerStyle, parsed_rules, None, ttsPreset)

    return ConvertResponse(
        job_id=job_id,
        status="pending",
        message="Podcast-Erstellung gestartet"
    )


@app.post("/convert-pack", response_model=ConvertResponse)
async def convert_pack(
    background_tasks: BackgroundTasks,
    request: ConvertPackRequest = Body(...),
    style: str = Query(default="dialog", regex="^(dialog|monolog)$"),
    speakerStyle: str = Query(default="sachlich", regex="^(sachlich|lebendig|lustig|locker)$"),
    ttsEngine: Optional[str] = Query(default=None),
    ttsPreset: str = Query(default="lebendig", regex="^(klar|lebendig|dynamisch)$"),
):
    """
    Convert a precomputed summary pack (from pdfua-service) to a podcast.

    This avoids PPTX parsing and VLM image descriptions, and is the preferred path for speed.
    """
    if not request.pack or not isinstance(request.pack, dict):
        raise HTTPException(status_code=400, detail="Pack erforderlich")

    # Validate TTS engine if provided
    valid_engines = {"xtts", "qwen3tts", "piper"}
    if ttsEngine:
        ttsEngine = ttsEngine.lower()
        if ttsEngine not in valid_engines:
            raise HTTPException(status_code=400, detail="Ungueltige TTS-Engine")

    job_id = str(uuid.uuid4())
    jobs[job_id] = {
        "job_id": job_id,
        "filename": (request.pack.get("document", {}) or {}).get("title") or "podcast",
        "style": style,
        "speaker_style": speakerStyle,
        "tts_preset": ttsPreset,
        "pipeline_path": "pack",
        "status": "pending",
        "progress": 0,
        "current_stage": "In Warteschlange...",
        "created_at": datetime.utcnow().isoformat(),
        "completed_at": None,
        "error": None,
        "output_path": None,
        "duration_seconds": None,
        "timings": {"scriptMs": 0, "ttsMs": 0, "totalMs": 0},
    }

    background_tasks.add_task(
        process_podcast_from_pack,
        job_id,
        request.pack,
        style,
        speakerStyle,
        request.pronunciationRules,
        ttsEngine,
        ttsPreset,
    )

    return ConvertResponse(
        job_id=job_id,
        status="pending",
        message="Podcast-Erstellung gestartet",
    )


@app.get("/status/{job_id}")
async def get_job_status(job_id: str):
    """Get the status of a podcast conversion job."""
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job nicht gefunden")

    job = jobs[job_id]
    return {
        "job_id": job_id,
        "status": job["status"],
        "phase_code": job.get("status"),
        "phase_message": job.get("current_stage"),
        "progress": job["progress"],
        "current_stage": job["current_stage"],
        "pipeline_path": job.get("pipeline_path"),
        "timings": job.get("timings"),
        "created_at": job["created_at"],
        "completed_at": job.get("completed_at"),
        "duration_seconds": job.get("duration_seconds"),
        "error": job.get("error"),
        "chapters": job.get("chapters"),
    }


@app.get("/download/{job_id}")
async def download_podcast(job_id: str):
    """Download the completed podcast file."""
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job nicht gefunden")

    job = jobs[job_id]

    if job["status"] != "completed":
        raise HTTPException(
            status_code=400,
            detail=f"Podcast nicht bereit. Status: {job['status']}"
        )

    output_path = job.get("output_path")
    if not output_path or not os.path.exists(output_path):
        raise HTTPException(status_code=404, detail="Datei nicht gefunden")

    # Generate nice filename
    original_name = job.get("filename", "podcast")
    base_name = original_name.rsplit(".", 1)[0]
    download_name = f"{base_name}_podcast.mp3"

    return FileResponse(
        path=output_path,
        media_type="audio/mpeg",
        filename=download_name,
    )


@app.get("/voices")
async def get_voices():
    """List available TTS voices."""
    voices = list_available_voices()
    return {
        "voices": voices,
        "configured": {
            "host": PIPER_CONFIG["host_voice"],
            "expert": PIPER_CONFIG["expert_voice"],
            "narrator": PIPER_CONFIG["narrator_voice"],
        },
    }


# =============================================================================
# Voice-Over Endpoints
# =============================================================================

# Voice-over job storage (separate from podcast jobs)
voiceover_jobs: Dict[str, Dict[str, Any]] = {}


class VoiceOverRequest(BaseModel):
    text: str
    voice: str = "female"  # "male" or "female"
    pronunciationRules: Optional[List[Dict[str, str]]] = None
    ttsEngine: Optional[str] = None


class VoiceOverResponse(BaseModel):
    job_id: str
    status: str
    message: str


async def process_voiceover(
    job_id: str,
    text: str,
    voice: str,
    pronunciation_rules: Optional[List[Dict[str, str]]] = None,
    tts_engine: Optional[str] = None,
):
    """Background task to generate voice-over audio."""
    try:
        voiceover_jobs[job_id]["status"] = "processing"
        voiceover_jobs[job_id]["current_stage"] = "Audio wird generiert..."
        voiceover_jobs[job_id]["progress"] = 5

        output_path = os.path.join(OUTPUT_DIR, f"voiceover_{job_id}.mp3")

        def progress_callback(percent, stage):
            voiceover_jobs[job_id]["progress"] = percent
            voiceover_jobs[job_id]["current_stage"] = stage

        # Run TTS generation in thread pool
        import asyncio
        loop = asyncio.get_event_loop()
        result = await loop.run_in_executor(
            None,
            lambda: generate_voiceover(
                text=text,
                voice=voice,
                pronunciation_rules=pronunciation_rules,
                output_path=output_path,
                progress_callback=progress_callback,
                tts_engine=tts_engine,
            )
        )

        if not result.get("success"):
            raise ValueError(result.get("error", "Voice-Over Generierung fehlgeschlagen"))

        voiceover_jobs[job_id]["status"] = "completed"
        voiceover_jobs[job_id]["current_stage"] = "Fertig"
        voiceover_jobs[job_id]["progress"] = 100
        voiceover_jobs[job_id]["completed_at"] = datetime.utcnow().isoformat()
        voiceover_jobs[job_id]["output_path"] = output_path
        voiceover_jobs[job_id]["duration_seconds"] = result.get("duration_seconds", 0)

    except Exception as e:
        voiceover_jobs[job_id]["status"] = "failed"
        voiceover_jobs[job_id]["error"] = str(e)
        voiceover_jobs[job_id]["current_stage"] = "Fehler"
        print(f"[VoiceOver] Job {job_id} failed: {e}")


@app.post("/voiceover/generate", response_model=VoiceOverResponse)
async def generate_voiceover_endpoint(
    background_tasks: BackgroundTasks,
    request: VoiceOverRequest,
):
    """
    Generate voice-over audio from text.

    - **text**: Text to synthesize (max 50,000 characters)
    - **voice**: "male" or "female"
    - **pronunciationRules**: Optional list of {"original": "...", "spoken": "..."} rules
    """
    if not request.text or not request.text.strip():
        raise HTTPException(status_code=400, detail="Kein Text angegeben")

    if len(request.text) > 50000:
        raise HTTPException(status_code=400, detail="Text zu lang (max. 50.000 Zeichen)")

    if request.voice not in ("male", "female"):
        raise HTTPException(status_code=400, detail="Ungueltige Stimme. Erlaubt: male, female")

    if request.ttsEngine:
        valid_engines = {"xtts", "qwen3tts", "piper"}
        if request.ttsEngine.lower() not in valid_engines:
            raise HTTPException(status_code=400, detail="Ungueltige TTS-Engine")

    job_id = str(uuid.uuid4())

    voiceover_jobs[job_id] = {
        "job_id": job_id,
        "status": "pending",
        "progress": 0,
        "current_stage": "In Warteschlange...",
        "created_at": datetime.utcnow().isoformat(),
        "completed_at": None,
        "error": None,
        "output_path": None,
        "duration_seconds": None,
        "voice": request.voice,
        "text_length": len(request.text),
    }

    background_tasks.add_task(
        process_voiceover,
        job_id,
        request.text,
        request.voice,
        request.pronunciationRules,
        request.ttsEngine,
    )

    return VoiceOverResponse(
        job_id=job_id,
        status="pending",
        message="Voice-Over Generierung gestartet",
    )


@app.get("/voiceover/status/{job_id}")
async def get_voiceover_status(job_id: str):
    """Get the status of a voice-over generation job."""
    if job_id not in voiceover_jobs:
        raise HTTPException(status_code=404, detail="Job nicht gefunden")

    job = voiceover_jobs[job_id]
    return {
        "job_id": job_id,
        "status": job["status"],
        "progress": job["progress"],
        "current_stage": job["current_stage"],
        "created_at": job["created_at"],
        "completed_at": job.get("completed_at"),
        "duration_seconds": job.get("duration_seconds"),
        "error": job.get("error"),
    }


@app.get("/voiceover/download/{job_id}")
async def download_voiceover(job_id: str):
    """Download the completed voice-over audio file."""
    if job_id not in voiceover_jobs:
        raise HTTPException(status_code=404, detail="Job nicht gefunden")

    job = voiceover_jobs[job_id]

    if job["status"] != "completed":
        raise HTTPException(
            status_code=400,
            detail=f"Voice-Over nicht bereit. Status: {job['status']}"
        )

    output_path = job.get("output_path")
    if not output_path or not os.path.exists(output_path):
        raise HTTPException(status_code=404, detail="Datei nicht gefunden")

    return FileResponse(
        path=output_path,
        media_type="audio/mpeg",
        filename="voiceover.mp3",
    )


@app.post("/voiceover/extract-text")
async def extract_text_endpoint(file: UploadFile = File(...)):
    """
    Extract text from a Word document (.docx).

    - **file**: Word document file (.docx)
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="Dateiname erforderlich")

    ext = file.filename.lower().split(".")[-1]
    if ext not in ["docx", "doc"]:
        raise HTTPException(
            status_code=400,
            detail=f"Ungueltiger Dateityp: {ext}. Unterstuetzt: DOCX"
        )

    # Save file temporarily
    temp_path = os.path.join(UPLOAD_DIR, f"temp_{uuid.uuid4()}_{file.filename}")

    try:
        content = await file.read()
        with open(temp_path, "wb") as f:
            f.write(content)

        # Extract text
        result = extract_text_from_docx(temp_path)

        if not result.get("success"):
            raise HTTPException(status_code=400, detail=result.get("error", "Extraktion fehlgeschlagen"))

        return {
            "text": result["text"],
            "word_count": result["word_count"],
            "paragraph_count": result["paragraph_count"],
            "metadata": result.get("metadata", {}),
        }

    finally:
        # Cleanup
        if os.path.exists(temp_path):
            os.remove(temp_path)


# =============================================================================
# Startup and Cleanup
# =============================================================================

# Cleanup old jobs periodically
@app.on_event("startup")
async def startup():
    """Cleanup old files and preload XTTS model on startup."""
    # Cleanup old output files
    try:
        import time
        now = time.time()
        for f in os.listdir(OUTPUT_DIR):
            path = os.path.join(OUTPUT_DIR, f)
            if os.path.isfile(path):
                age = now - os.path.getmtime(path)
                if age > 24 * 60 * 60:
                    os.remove(path)
    except Exception as e:
        print(f"[Podcast] Cleanup error: {e}")

    # Preload XTTS model in background to avoid slow first request
    import asyncio
    asyncio.create_task(_preload_xtts())


async def _preload_xtts():
    """Preload XTTS model in background."""
    import asyncio
    from app.config import TTS_ENGINE

    if TTS_ENGINE != "xtts" or os.getenv("XTTS_PRELOAD", "true").lower() != "true":
        print("[Podcast] TTS engine is not XTTS, skipping preload")
        return

    print("[Podcast] Preloading XTTS model...")
    try:
        # Run model loading in thread pool to not block event loop
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(None, _load_xtts_model)
        print("[Podcast] XTTS model preloaded successfully")
    except Exception as e:
        print(f"[Podcast] XTTS preload failed: {e}")


def _load_xtts_model():
    """Load XTTS model (runs in thread pool)."""
    from app.generators.xtts_generator import get_xtts_generator
    xtts = get_xtts_generator()
    if xtts.is_available():
        # Force initialization
        xtts._ensure_initialized()
