// EN 301 549 V3.2.1 Kriterien - Kapitel 9 (Web) + Kapitel 10 (Dokumente)
// Basierend auf WCAG 2.1 Level A und AA

import db from './init';

interface CriterionSeed {
  id: string;
  chapter: 9 | 10;
  section: string;
  title_de: string;
  title_en: string;
  description_de: string;
  level: 'A' | 'AA' | 'AAA';
  wcag_criterion: string | null;
  bitv_reference: string | null;
  applies_to: string[];
  is_additional: boolean;
  testing_guidance_de: string | null;
}

// Kapitel 9 - Web (WCAG 2.1 Kriterien)
const CHAPTER_9_CRITERIA: CriterionSeed[] = [
  // 1.1 Textalternativen
  {
    id: '9.1.1.1',
    chapter: 9,
    section: '1.1.1',
    title_de: 'Nicht-Text-Inhalt',
    title_en: 'Non-text Content',
    description_de: 'Alle Nicht-Text-Inhalte, die dem Benutzer präsentiert werden, haben eine Textalternative, die einem äquivalenten Zweck dient. Ausnahmen: Steuerelemente, Eingabe, zeitbasierte Medien, Tests, sensorische Inhalte, CAPTCHA, Dekoration.',
    level: 'A',
    wcag_criterion: '1.1.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.1.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie alle Bilder, Icons, Grafiken und Multimedia-Inhalte auf aussagekräftige alt-Attribute oder aria-label.',
  },

  // 1.2 Zeitbasierte Medien
  {
    id: '9.1.2.1',
    chapter: 9,
    section: '1.2.1',
    title_de: 'Nur-Audio und Nur-Video (aufgezeichnet)',
    title_en: 'Audio-only and Video-only (Prerecorded)',
    description_de: 'Für aufgezeichnete Nur-Audio- und Nur-Video-Inhalte gibt es eine Alternative (Transkript für Audio, Audiodeskription oder Textbeschreibung für Video).',
    level: 'A',
    wcag_criterion: '1.2.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.2.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Podcasts ein Transkript haben und Videos ohne Ton eine Textbeschreibung.',
  },
  {
    id: '9.1.2.2',
    chapter: 9,
    section: '1.2.2',
    title_de: 'Untertitel (aufgezeichnet)',
    title_en: 'Captions (Prerecorded)',
    description_de: 'Für alle aufgezeichneten Audio-Inhalte in synchronisierten Medien werden Untertitel bereitgestellt.',
    level: 'A',
    wcag_criterion: '1.2.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.2.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie alle Videos auf korrekte, synchrone Untertitel.',
  },
  {
    id: '9.1.2.3',
    chapter: 9,
    section: '1.2.3',
    title_de: 'Audiodeskription oder Medienalternative (aufgezeichnet)',
    title_en: 'Audio Description or Media Alternative (Prerecorded)',
    description_de: 'Eine Alternative für zeitbasierte Medien oder Audiodeskription wird für aufgezeichnete Video-Inhalte bereitgestellt.',
    level: 'A',
    wcag_criterion: '1.2.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.2.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Videos eine Audiodeskription oder ein vollständiges Transkript haben.',
  },
  {
    id: '9.1.2.4',
    chapter: 9,
    section: '1.2.4',
    title_de: 'Untertitel (Live)',
    title_en: 'Captions (Live)',
    description_de: 'Für alle Live-Audio-Inhalte in synchronisierten Medien werden Untertitel bereitgestellt.',
    level: 'AA',
    wcag_criterion: '1.2.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.2.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Live-Streams und Webinare auf Echtzeit-Untertitel.',
  },
  {
    id: '9.1.2.5',
    chapter: 9,
    section: '1.2.5',
    title_de: 'Audiodeskription (aufgezeichnet)',
    title_en: 'Audio Description (Prerecorded)',
    description_de: 'Audiodeskription wird für alle aufgezeichneten Video-Inhalte bereitgestellt.',
    level: 'AA',
    wcag_criterion: '1.2.5',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.2.5',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Videos auf Audiodeskription für visuelle Inhalte.',
  },

  // 1.3 Anpassbar
  {
    id: '9.1.3.1',
    chapter: 9,
    section: '1.3.1',
    title_de: 'Info und Beziehungen',
    title_en: 'Info and Relationships',
    description_de: 'Informationen, Struktur und Beziehungen, die durch Darstellung vermittelt werden, können programmatisch bestimmt werden oder sind im Text verfügbar.',
    level: 'A',
    wcag_criterion: '1.3.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Überschriften (h1-h6), Listen, Tabellen und Formulare auf korrekte semantische Auszeichnung.',
  },
  {
    id: '9.1.3.2',
    chapter: 9,
    section: '1.3.2',
    title_de: 'Bedeutungstragende Reihenfolge',
    title_en: 'Meaningful Sequence',
    description_de: 'Wenn die Reihenfolge, in der Inhalte präsentiert werden, ihre Bedeutung beeinflusst, kann eine korrekte Lesereihenfolge programmatisch bestimmt werden.',
    level: 'A',
    wcag_criterion: '1.3.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie die DOM-Reihenfolge und ob sie der visuellen Reihenfolge entspricht.',
  },
  {
    id: '9.1.3.3',
    chapter: 9,
    section: '1.3.3',
    title_de: 'Sensorische Eigenschaften',
    title_en: 'Sensory Characteristics',
    description_de: 'Anweisungen zum Verstehen und Bedienen von Inhalten verlassen sich nicht ausschließlich auf sensorische Merkmale wie Form, Farbe, Größe, Position, Ausrichtung oder Ton.',
    level: 'A',
    wcag_criterion: '1.3.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Anweisungen wie "Klicken Sie auf den grünen Button" auf zusätzliche Identifikationsmerkmale.',
  },
  {
    id: '9.1.3.4',
    chapter: 9,
    section: '1.3.4',
    title_de: 'Ausrichtung',
    title_en: 'Orientation',
    description_de: 'Inhalte schraenken ihre Ansicht und Bedienung nicht auf eine einzige Anzeigeausrichtung ein.',
    level: 'AA',
    wcag_criterion: '1.3.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Testen Sie die Seite im Hoch- und Querformat.',
  },
  {
    id: '9.1.3.5',
    chapter: 9,
    section: '1.3.5',
    title_de: 'Eingabezweck bestimmen',
    title_en: 'Identify Input Purpose',
    description_de: 'Der Zweck jedes Eingabefeldes, das persönliche Daten des Nutzers sammelt, kann programmatisch bestimmt werden.',
    level: 'AA',
    wcag_criterion: '1.3.5',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.5',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Formulare auf autocomplete-Attribute (z.B. autocomplete="email").',
  },

  // 1.4 Unterscheidbar
  {
    id: '9.1.4.1',
    chapter: 9,
    section: '1.4.1',
    title_de: 'Benutzung von Farbe',
    title_en: 'Use of Color',
    description_de: 'Farbe wird nicht als einziges visuelles Mittel verwendet, um Informationen zu vermitteln, eine Aktion anzuzeigen, eine Antwort zu verlangen oder ein visuelles Element zu unterscheiden.',
    level: 'A',
    wcag_criterion: '1.4.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Fehlermeldungen, Links und Diagramme auf zusätzliche Kennzeichnung neben Farbe.',
  },
  {
    id: '9.1.4.2',
    chapter: 9,
    section: '1.4.2',
    title_de: 'Audio-Steuerung',
    title_en: 'Audio Control',
    description_de: 'Wenn Audio automatisch abgespielt wird, gibt es einen Mechanismus zum Pausieren, Stoppen oder Anpassen der Lautstärke.',
    level: 'A',
    wcag_criterion: '1.4.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob automatisch abspielende Medien pausiert werden können.',
  },
  {
    id: '9.1.4.3',
    chapter: 9,
    section: '1.4.3',
    title_de: 'Kontrast (Minimum)',
    title_en: 'Contrast (Minimum)',
    description_de: 'Die visuelle Darstellung von Text und Bildern von Text hat ein Kontrastverhältnis von mindestens 4,5:1. Großer Text (ab 18pt oder 14pt fett) mindestens 3:1.',
    level: 'AA',
    wcag_criterion: '1.4.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Nutzen Sie den VoxDrop Kontrastchecker oder ein Browser-Plugin.',
  },
  {
    id: '9.1.4.4',
    chapter: 9,
    section: '1.4.4',
    title_de: 'Textgröße ändern',
    title_en: 'Resize Text',
    description_de: 'Text kann ohne assistive Technologie auf 200% vergrößert werden, ohne dass Inhalt oder Funktionalität verloren geht.',
    level: 'AA',
    wcag_criterion: '1.4.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Zoomen Sie die Seite auf 200% und prüfen Sie auf Überlappungen.',
  },
  {
    id: '9.1.4.5',
    chapter: 9,
    section: '1.4.5',
    title_de: 'Bilder von Text',
    title_en: 'Images of Text',
    description_de: 'Wenn die verwendeten Technologien die visuelle Darstellung erreichen können, wird Text verwendet, um Informationen zu vermitteln, nicht Bilder von Text.',
    level: 'AA',
    wcag_criterion: '1.4.5',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.5',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Text als HTML statt als Bild dargestellt wird.',
  },
  {
    id: '9.1.4.10',
    chapter: 9,
    section: '1.4.10',
    title_de: 'Umfließen (Reflow)',
    title_en: 'Reflow',
    description_de: 'Inhalte können ohne Verlust von Informationen bei einer Breite von 320 CSS-Pixeln (entspricht 400% Zoom) dargestellt werden.',
    level: 'AA',
    wcag_criterion: '1.4.10',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.10',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Testen Sie die Seite bei 320px Breite oder 400% Zoom.',
  },
  {
    id: '9.1.4.11',
    chapter: 9,
    section: '1.4.11',
    title_de: 'Nicht-Text-Kontrast',
    title_en: 'Non-text Contrast',
    description_de: 'UI-Komponenten und grafische Objekte haben ein Kontrastverhältnis von mindestens 3:1 gegen angrenzende Farben.',
    level: 'AA',
    wcag_criterion: '1.4.11',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.11',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Buttons, Icons und Formularfelder auf ausreichenden Kontrast.',
  },
  {
    id: '9.1.4.12',
    chapter: 9,
    section: '1.4.12',
    title_de: 'Textabstand',
    title_en: 'Text Spacing',
    description_de: 'Bei Anpassung von Zeilenhöhe, Absatz-, Buchstaben- und Wortabstand geht kein Inhalt oder keine Funktionalität verloren.',
    level: 'AA',
    wcag_criterion: '1.4.12',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.12',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Testen Sie mit einem Text-Spacing-Bookmarklet.',
  },
  {
    id: '9.1.4.13',
    chapter: 9,
    section: '1.4.13',
    title_de: 'Inhalt bei Hover oder Fokus',
    title_en: 'Content on Hover or Focus',
    description_de: 'Zusätzliche Inhalte, die bei Hover oder Fokus erscheinen, sind verwerfbar, hoverbar und persistent.',
    level: 'AA',
    wcag_criterion: '1.4.13',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.13',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Tooltips und Dropdown-Menüs auf Bedienbarkeit.',
  },

  // 2.1 Tastaturbedienbar
  {
    id: '9.2.1.1',
    chapter: 9,
    section: '2.1.1',
    title_de: 'Tastatur',
    title_en: 'Keyboard',
    description_de: 'Alle Funktionalitäten sind über eine Tastatur bedienbar, ohne dass bestimmte Zeitvorgaben für einzelne Tastenanschläge erforderlich sind.',
    level: 'A',
    wcag_criterion: '2.1.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.1.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Navigieren Sie die gesamte Seite nur mit Tab, Enter und Pfeiltasten.',
  },
  {
    id: '9.2.1.2',
    chapter: 9,
    section: '2.1.2',
    title_de: 'Keine Tastaturfalle',
    title_en: 'No Keyboard Trap',
    description_de: 'Wenn der Tastaturfokus mit der Tastatur zu einer Komponente bewegt werden kann, kann er auch mit der Tastatur wieder wegbewegt werden.',
    level: 'A',
    wcag_criterion: '2.1.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.1.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Sie aus allen Elementen (Modals, Iframes) mit Tab herausnavigieren können.',
  },
  {
    id: '9.2.1.4',
    chapter: 9,
    section: '2.1.4',
    title_de: 'Tastaturkürzel',
    title_en: 'Character Key Shortcuts',
    description_de: 'Wenn Tastaturkürzel nur mit Zeichentasten implementiert sind, können sie deaktiviert oder neu zugewiesen werden.',
    level: 'A',
    wcag_criterion: '2.1.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.1.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Einzeltasten-Shortcuts konfigurierbar sind.',
  },

  // 2.2 Ausreichend Zeit
  {
    id: '9.2.2.1',
    chapter: 9,
    section: '2.2.1',
    title_de: 'Zeiteinteilung anpassbar',
    title_en: 'Timing Adjustable',
    description_de: 'Für zeitgesteuerte Inhalte kann der Nutzer die Zeit ausschalten, anpassen oder verlängern.',
    level: 'A',
    wcag_criterion: '2.2.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.2.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Session-Timeouts, Formulare und automatische Weiterleitungen.',
  },
  {
    id: '9.2.2.2',
    chapter: 9,
    section: '2.2.2',
    title_de: 'Pausieren, Stoppen, Ausblenden',
    title_en: 'Pause, Stop, Hide',
    description_de: 'Für sich bewegende, blinkende oder automatisch aktualisierte Informationen gibt es einen Mechanismus zum Pausieren, Stoppen oder Ausblenden.',
    level: 'A',
    wcag_criterion: '2.2.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.2.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Karussells, Animationen und Live-Ticker auf Pause-Funktion.',
  },

  // 2.3 Anfälle und körperliche Reaktionen
  {
    id: '9.2.3.1',
    chapter: 9,
    section: '2.3.1',
    title_de: 'Dreimaliges Blitzen oder unterhalb Grenzwert',
    title_en: 'Three Flashes or Below Threshold',
    description_de: 'Webseiten enthalten nichts, das öfter als dreimal in einer Sekunde blitzt.',
    level: 'A',
    wcag_criterion: '2.3.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.3.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Videos und Animationen auf schnell blinkende Inhalte.',
  },

  // 2.4 Navigierbar
  {
    id: '9.2.4.1',
    chapter: 9,
    section: '2.4.1',
    title_de: 'Bloecke umgehen',
    title_en: 'Bypass Blocks',
    description_de: 'Ein Mechanismus ist verfügbar, um Bloecke von Inhalten zu umgehen, die auf mehreren Webseiten wiederholt werden.',
    level: 'A',
    wcag_criterion: '2.4.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie auf Skip-Links ("Zum Inhalt springen").',
  },
  {
    id: '9.2.4.2',
    chapter: 9,
    section: '2.4.2',
    title_de: 'Seite betitelt',
    title_en: 'Page Titled',
    description_de: 'Webseiten haben Titel, die Thema oder Zweck beschreiben.',
    level: 'A',
    wcag_criterion: '2.4.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie das <title>-Element im Browser-Tab.',
  },
  {
    id: '9.2.4.3',
    chapter: 9,
    section: '2.4.3',
    title_de: 'Fokusreihenfolge',
    title_en: 'Focus Order',
    description_de: 'Wenn eine Webseite sequenziell navigiert werden kann, erhalten Komponenten den Fokus in einer Reihenfolge, die Bedeutung und Bedienbarkeit erhält.',
    level: 'A',
    wcag_criterion: '2.4.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Navigieren Sie mit Tab durch die Seite und prüfen Sie die logische Reihenfolge.',
  },
  {
    id: '9.2.4.4',
    chapter: 9,
    section: '2.4.4',
    title_de: 'Linkzweck (im Kontext)',
    title_en: 'Link Purpose (In Context)',
    description_de: 'Der Zweck jedes Links kann aus dem Linktext allein oder zusammen mit dem programmatisch bestimmbaren Kontext bestimmt werden.',
    level: 'A',
    wcag_criterion: '2.4.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Linktexte wie "hier" oder "mehr" auf aussagekräftige Beschreibung.',
  },
  {
    id: '9.2.4.5',
    chapter: 9,
    section: '2.4.5',
    title_de: 'Verschiedene Methoden',
    title_en: 'Multiple Ways',
    description_de: 'Es gibt mehr als eine Methode, um eine Webseite innerhalb einer Sammlung von Webseiten zu finden (Sitemap, Suche, Inhaltsverzeichnis).',
    level: 'AA',
    wcag_criterion: '2.4.5',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.5',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie auf Suchfunktion, Sitemap oder Navigation.',
  },
  {
    id: '9.2.4.6',
    chapter: 9,
    section: '2.4.6',
    title_de: 'Überschriften und Labels',
    title_en: 'Headings and Labels',
    description_de: 'Überschriften und Labels beschreiben das Thema oder den Zweck.',
    level: 'AA',
    wcag_criterion: '2.4.6',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.6',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Überschriften und Formularlabels auf aussagekräftige Beschreibung.',
  },
  {
    id: '9.2.4.7',
    chapter: 9,
    section: '2.4.7',
    title_de: 'Sichtbarer Fokus',
    title_en: 'Focus Visible',
    description_de: 'Jede per Tastatur bedienbare Benutzeroberfläche hat einen sichtbaren Tastaturfokus.',
    level: 'AA',
    wcag_criterion: '2.4.7',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.7',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Navigieren Sie mit Tab und prüfen Sie, ob der Fokus immer sichtbar ist.',
  },

  // 2.5 Eingabemodalitäten
  {
    id: '9.2.5.1',
    chapter: 9,
    section: '2.5.1',
    title_de: 'Zeigergesten',
    title_en: 'Pointer Gestures',
    description_de: 'Alle Funktionen, die Mehrpunkt- oder pfadbasierte Gesten nutzen, können auch mit einer Einzelpunktgeste bedient werden.',
    level: 'A',
    wcag_criterion: '2.5.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.5.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Pinch-to-Zoom und Swipe-Gesten auf Alternativen.',
  },
  {
    id: '9.2.5.2',
    chapter: 9,
    section: '2.5.2',
    title_de: 'Abbruch der Zeigereingabe',
    title_en: 'Pointer Cancellation',
    description_de: 'Für Funktionen, die mit einem Zeiger bedient werden, ist mindestens eine der folgenden Bedingungen erfüllt: kein Down-Event, Abbruch möglich, Umkehrung möglich, oder wesentlich.',
    level: 'A',
    wcag_criterion: '2.5.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.5.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Buttons auf mouseup/touchend statt mousedown reagieren.',
  },
  {
    id: '9.2.5.3',
    chapter: 9,
    section: '2.5.3',
    title_de: 'Label im Namen',
    title_en: 'Label in Name',
    description_de: 'Bei UI-Komponenten mit sichtbarem Text enthält der zugängliche Name den sichtbaren Text.',
    level: 'A',
    wcag_criterion: '2.5.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.5.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob aria-label den sichtbaren Text enthält.',
  },
  {
    id: '9.2.5.4',
    chapter: 9,
    section: '2.5.4',
    title_de: 'Bewegungsaktivierung',
    title_en: 'Motion Actuation',
    description_de: 'Funktionen, die durch Gerätebewegung ausgelöst werden, können auch über UI-Komponenten bedient werden.',
    level: 'A',
    wcag_criterion: '2.5.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.5.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Schütteln- oder Neigungsfunktionen auf Button-Alternativen.',
  },

  // 3.1 Lesbar
  {
    id: '9.3.1.1',
    chapter: 9,
    section: '3.1.1',
    title_de: 'Sprache der Seite',
    title_en: 'Language of Page',
    description_de: 'Die voreingestellte menschliche Sprache jeder Webseite kann programmatisch bestimmt werden.',
    level: 'A',
    wcag_criterion: '3.1.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.1.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie das lang-Attribut im <html>-Tag.',
  },
  {
    id: '9.3.1.2',
    chapter: 9,
    section: '3.1.2',
    title_de: 'Sprache von Teilen',
    title_en: 'Language of Parts',
    description_de: 'Die menschliche Sprache jedes Abschnitts oder jeder Phrase kann programmatisch bestimmt werden.',
    level: 'AA',
    wcag_criterion: '3.1.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.1.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie fremdsprachige Textpassagen auf lang-Attribut.',
  },

  // 3.2 Vorhersehbar
  {
    id: '9.3.2.1',
    chapter: 9,
    section: '3.2.1',
    title_de: 'Bei Fokus',
    title_en: 'On Focus',
    description_de: 'Wenn eine Komponente den Fokus erhält, löst dies keine Kontextänderung aus.',
    level: 'A',
    wcag_criterion: '3.2.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.2.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob bei Tab-Navigation keine unerwarteten Popups oder Weiterleitungen erfolgen.',
  },
  {
    id: '9.3.2.2',
    chapter: 9,
    section: '3.2.2',
    title_de: 'Bei Eingabe',
    title_en: 'On Input',
    description_de: 'Das Ändern einer UI-Komponente löst automatisch keine Kontextänderung aus, es sei denn, der Benutzer wurde vorher informiert.',
    level: 'A',
    wcag_criterion: '3.2.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.2.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Dropdown-Menüs auf automatische Weiterleitung bei Auswahl.',
  },
  {
    id: '9.3.2.3',
    chapter: 9,
    section: '3.2.3',
    title_de: 'Konsistente Navigation',
    title_en: 'Consistent Navigation',
    description_de: 'Navigationsmechanismen, die auf mehreren Webseiten wiederholt werden, erscheinen in der gleichen relativen Reihenfolge.',
    level: 'AA',
    wcag_criterion: '3.2.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.2.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Vergleichen Sie die Navigation auf verschiedenen Unterseiten.',
  },
  {
    id: '9.3.2.4',
    chapter: 9,
    section: '3.2.4',
    title_de: 'Konsistente Identifikation',
    title_en: 'Consistent Identification',
    description_de: 'Komponenten mit gleicher Funktionalität werden konsistent identifiziert.',
    level: 'AA',
    wcag_criterion: '3.2.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.2.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob gleiche Funktionen gleiche Labels haben (z.B. Suche).',
  },

  // 3.3 Hilfestellung bei der Eingabe
  {
    id: '9.3.3.1',
    chapter: 9,
    section: '3.3.1',
    title_de: 'Fehlererkennung',
    title_en: 'Error Identification',
    description_de: 'Wenn ein Eingabefehler automatisch erkannt wird, wird das fehlerhafte Element identifiziert und der Fehler in Text beschrieben.',
    level: 'A',
    wcag_criterion: '3.3.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.3.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Senden Sie ein Formular mit Fehlern ab und prüfen Sie die Fehlermeldungen.',
  },
  {
    id: '9.3.3.2',
    chapter: 9,
    section: '3.3.2',
    title_de: 'Labels oder Anweisungen',
    title_en: 'Labels or Instructions',
    description_de: 'Labels oder Anweisungen werden bereitgestellt, wenn Inhalte Benutzereingaben erfordern.',
    level: 'A',
    wcag_criterion: '3.3.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.3.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie alle Formularfelder auf sichtbare Labels.',
  },
  {
    id: '9.3.3.3',
    chapter: 9,
    section: '3.3.3',
    title_de: 'Fehlervorschläge',
    title_en: 'Error Suggestion',
    description_de: 'Wenn ein Eingabefehler erkannt wird und Korrekturvorschläge bekannt sind, werden diese dem Benutzer bereitgestellt.',
    level: 'AA',
    wcag_criterion: '3.3.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.3.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Fehlermeldungen Korrekturhinweise enthalten.',
  },
  {
    id: '9.3.3.4',
    chapter: 9,
    section: '3.3.4',
    title_de: 'Fehlervermeidung (rechtlich, finanziell, Daten)',
    title_en: 'Error Prevention (Legal, Financial, Data)',
    description_de: 'Für rechtlich bindende oder finanzielle Transaktionen: Eingaben sind umkehrbar, werden geprüft oder können bestätigt werden.',
    level: 'AA',
    wcag_criterion: '3.3.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.3.4',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Bestellvorgänge auf Bestätigungsschritt.',
  },

  // 4.1 Kompatibel
  {
    id: '9.4.1.1',
    chapter: 9,
    section: '4.1.1',
    title_de: 'Parsing',
    title_en: 'Parsing',
    description_de: 'In Markup-Sprachen haben Elemente vollständige Start- und End-Tags, sind korrekt verschachtelt und haben keine doppelten Attribute.',
    level: 'A',
    wcag_criterion: '4.1.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 4.1.1',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Validieren Sie den HTML-Code mit dem W3C-Validator.',
  },
  {
    id: '9.4.1.2',
    chapter: 9,
    section: '4.1.2',
    title_de: 'Name, Rolle, Wert',
    title_en: 'Name, Role, Value',
    description_de: 'Für alle UI-Komponenten können Name und Rolle programmatisch bestimmt werden; Zustände und Werte können programmatisch gesetzt werden.',
    level: 'A',
    wcag_criterion: '4.1.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 4.1.2',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie mit Screenreader, ob alle interaktiven Elemente korrekt angesagt werden.',
  },
  {
    id: '9.4.1.3',
    chapter: 9,
    section: '4.1.3',
    title_de: 'Statusmeldungen',
    title_en: 'Status Messages',
    description_de: 'Statusmeldungen können programmatisch bestimmt werden, ohne Fokus zu erhalten.',
    level: 'AA',
    wcag_criterion: '4.1.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 4.1.3',
    applies_to: ['web'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Erfolgs-/Fehlermeldungen auf role="alert" oder aria-live.',
  },
];

// Kapitel 10 - Dokumente (auf WCAG 2.1 basierend)
const CHAPTER_10_CRITERIA: CriterionSeed[] = [
  // 1.1 Textalternativen
  {
    id: '10.1.1.1',
    chapter: 10,
    section: '1.1.1',
    title_de: 'Nicht-Text-Inhalt (Dokumente)',
    title_en: 'Non-text Content (Documents)',
    description_de: 'Alle Nicht-Text-Inhalte in Dokumenten haben eine Textalternative, die einem äquivalenten Zweck dient.',
    level: 'A',
    wcag_criterion: '1.1.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.1.1',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie alle Bilder in PDF/Word auf Alt-Text.',
  },

  // 1.3 Anpassbar
  {
    id: '10.1.3.1',
    chapter: 10,
    section: '1.3.1',
    title_de: 'Info und Beziehungen (Dokumente)',
    title_en: 'Info and Relationships (Documents)',
    description_de: 'Informationen, Struktur und Beziehungen in Dokumenten können programmatisch bestimmt werden.',
    level: 'A',
    wcag_criterion: '1.3.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.1',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie PDF-Tags und Word-Formatvorlagen für Überschriften, Listen, Tabellen.',
  },
  {
    id: '10.1.3.2',
    chapter: 10,
    section: '1.3.2',
    title_de: 'Bedeutungstragende Reihenfolge (Dokumente)',
    title_en: 'Meaningful Sequence (Documents)',
    description_de: 'Die Lesereihenfolge in Dokumenten ist korrekt und kann programmatisch bestimmt werden.',
    level: 'A',
    wcag_criterion: '1.3.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.2',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie die Tag-Reihenfolge im PDF oder aktivieren Sie den Screenreader.',
  },
  {
    id: '10.1.3.3',
    chapter: 10,
    section: '1.3.3',
    title_de: 'Sensorische Eigenschaften (Dokumente)',
    title_en: 'Sensory Characteristics (Documents)',
    description_de: 'Anweisungen in Dokumenten verlassen sich nicht nur auf Farbe, Form oder Position.',
    level: 'A',
    wcag_criterion: '1.3.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.3.3',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Anweisungen wie "siehe roten Kasten" auf zusätzliche Beschreibung.',
  },

  // 1.4 Unterscheidbar
  {
    id: '10.1.4.1',
    chapter: 10,
    section: '1.4.1',
    title_de: 'Benutzung von Farbe (Dokumente)',
    title_en: 'Use of Color (Documents)',
    description_de: 'Farbe wird nicht als einziges Mittel verwendet, um Informationen in Dokumenten zu vermitteln.',
    level: 'A',
    wcag_criterion: '1.4.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.1',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Diagramme und hervorgehobenen Text auf zusätzliche Markierung.',
  },
  {
    id: '10.1.4.3',
    chapter: 10,
    section: '1.4.3',
    title_de: 'Kontrast (Minimum) (Dokumente)',
    title_en: 'Contrast (Minimum) (Documents)',
    description_de: 'Text in Dokumenten hat ein Kontrastverhältnis von mindestens 4,5:1 (3:1 für großen Text).',
    level: 'AA',
    wcag_criterion: '1.4.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.3',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Textfarben gegen Hintergrund mit einem Kontrastchecker.',
  },
  {
    id: '10.1.4.5',
    chapter: 10,
    section: '1.4.5',
    title_de: 'Bilder von Text (Dokumente)',
    title_en: 'Images of Text (Documents)',
    description_de: 'Text in Dokumenten wird nicht als Bild dargestellt, wenn echter Text möglich ist.',
    level: 'AA',
    wcag_criterion: '1.4.5',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 1.4.5',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Text markierbar ist (kein eingescanntes Bild).',
  },

  // 2.1 Tastaturbedienbar
  {
    id: '10.2.1.1',
    chapter: 10,
    section: '2.1.1',
    title_de: 'Tastatur (Dokumente)',
    title_en: 'Keyboard (Documents)',
    description_de: 'Alle interaktiven Elemente in Dokumenten (Formularfelder, Links) sind per Tastatur bedienbar.',
    level: 'A',
    wcag_criterion: '2.1.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.1.1',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Navigieren Sie PDF-Formulare nur mit Tab-Taste.',
  },
  {
    id: '10.2.1.2',
    chapter: 10,
    section: '2.1.2',
    title_de: 'Keine Tastaturfalle (Dokumente)',
    title_en: 'No Keyboard Trap (Documents)',
    description_de: 'In Dokumenten gibt es keine Tastaturfallen.',
    level: 'A',
    wcag_criterion: '2.1.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.1.2',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie, ob Sie aus allen Formularfeldern herausnavigieren können.',
  },

  // 2.4 Navigierbar
  {
    id: '10.2.4.2',
    chapter: 10,
    section: '2.4.2',
    title_de: 'Dokumenttitel',
    title_en: 'Document Titled',
    description_de: 'Dokumente haben einen aussagekräftigen Titel.',
    level: 'A',
    wcag_criterion: '2.4.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.2',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie die Dokumenteigenschaften auf Titel.',
  },
  {
    id: '10.2.4.3',
    chapter: 10,
    section: '2.4.3',
    title_de: 'Fokusreihenfolge (Dokumente)',
    title_en: 'Focus Order (Documents)',
    description_de: 'Die Tab-Reihenfolge in PDF-Formularen folgt der visuellen Reihenfolge.',
    level: 'A',
    wcag_criterion: '2.4.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.3',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Navigieren Sie mit Tab durch Formularfelder und prüfen Sie die Reihenfolge.',
  },
  {
    id: '10.2.4.4',
    chapter: 10,
    section: '2.4.4',
    title_de: 'Linkzweck (Dokumente)',
    title_en: 'Link Purpose (Documents)',
    description_de: 'Der Zweck jedes Links in Dokumenten kann aus dem Linktext bestimmt werden.',
    level: 'A',
    wcag_criterion: '2.4.4',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.4',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Links in PDFs auf aussagekräftige Beschreibung.',
  },
  {
    id: '10.2.4.6',
    chapter: 10,
    section: '2.4.6',
    title_de: 'Überschriften und Labels (Dokumente)',
    title_en: 'Headings and Labels (Documents)',
    description_de: 'Überschriften und Labels in Dokumenten beschreiben das Thema oder den Zweck.',
    level: 'AA',
    wcag_criterion: '2.4.6',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 2.4.6',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Überschriften und Formular-Labels auf Aussagekraft.',
  },

  // 3.1 Lesbar
  {
    id: '10.3.1.1',
    chapter: 10,
    section: '3.1.1',
    title_de: 'Sprache des Dokuments',
    title_en: 'Language of Document',
    description_de: 'Die Sprache des Dokuments ist in den Metadaten angegeben.',
    level: 'A',
    wcag_criterion: '3.1.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.1.1',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie die Dokumenteigenschaften auf Spracheinstellung.',
  },
  {
    id: '10.3.1.2',
    chapter: 10,
    section: '3.1.2',
    title_de: 'Sprache von Teilen (Dokumente)',
    title_en: 'Language of Parts (Documents)',
    description_de: 'Fremdsprachige Passagen im Dokument sind entsprechend gekennzeichnet.',
    level: 'AA',
    wcag_criterion: '3.1.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.1.2',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie fremdsprachige Abschnitte auf Sprachauszeichnung.',
  },

  // 3.3 Hilfestellung bei der Eingabe
  {
    id: '10.3.3.1',
    chapter: 10,
    section: '3.3.1',
    title_de: 'Fehlererkennung (Dokumente)',
    title_en: 'Error Identification (Documents)',
    description_de: 'Fehler in PDF-Formularen werden identifiziert und in Text beschrieben.',
    level: 'A',
    wcag_criterion: '3.3.1',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.3.1',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Testen Sie die Formularvalidierung in PDF-Dokumenten.',
  },
  {
    id: '10.3.3.2',
    chapter: 10,
    section: '3.3.2',
    title_de: 'Labels oder Anweisungen (Dokumente)',
    title_en: 'Labels or Instructions (Documents)',
    description_de: 'Formularfelder in Dokumenten haben sichtbare Labels.',
    level: 'A',
    wcag_criterion: '3.3.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.3.2',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie alle Formularfelder auf korrekte Label-Zuordnung.',
  },
  {
    id: '10.3.3.3',
    chapter: 10,
    section: '3.3.3',
    title_de: 'Fehlervorschläge (Dokumente)',
    title_en: 'Error Suggestion (Documents)',
    description_de: 'Bei Formularfehlern werden Korrekturvorschläge bereitgestellt.',
    level: 'AA',
    wcag_criterion: '3.3.3',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 3.3.3',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Prüfen Sie Fehlermeldungen auf hilfreiche Korrekturhinweise.',
  },

  // 4.1 Kompatibel
  {
    id: '10.4.1.2',
    chapter: 10,
    section: '4.1.2',
    title_de: 'Name, Rolle, Wert (Dokumente)',
    title_en: 'Name, Role, Value (Documents)',
    description_de: 'Für alle Formularelemente in Dokumenten können Name und Rolle programmatisch bestimmt werden.',
    level: 'A',
    wcag_criterion: '4.1.2',
    bitv_reference: 'BITV 2.0 Anlage 1, Nr. 4.1.2',
    applies_to: ['pdf', 'document'],
    is_additional: false,
    testing_guidance_de: 'Testen Sie PDF-Formulare mit einem Screenreader.',
  },

  // Dokumentenspezifische EN 301 549 Anforderungen
  {
    id: '10.0.1',
    chapter: 10,
    section: '0.1',
    title_de: 'PDF/UA-Konformität',
    title_en: 'PDF/UA Conformance',
    description_de: 'PDF-Dokumente entsprechen dem PDF/UA-Standard (ISO 14289-1).',
    level: 'A',
    wcag_criterion: null,
    bitv_reference: null,
    applies_to: ['pdf'],
    is_additional: true,
    testing_guidance_de: 'Prüfen Sie mit dem PAC 2024 Tool auf PDF/UA-Konformität.',
  },
  {
    id: '10.0.2',
    chapter: 10,
    section: '0.2',
    title_de: 'Getaggte Struktur',
    title_en: 'Tagged Structure',
    description_de: 'Das Dokument enthält eine vollständige Tag-Struktur, die die logische Lesereihenfolge abbildet.',
    level: 'A',
    wcag_criterion: null,
    bitv_reference: null,
    applies_to: ['pdf', 'document'],
    is_additional: true,
    testing_guidance_de: 'Prüfen Sie den Tag-Baum in Adobe Acrobat Pro.',
  },
  {
    id: '10.0.3',
    chapter: 10,
    section: '0.3',
    title_de: 'Lesezeichen',
    title_en: 'Bookmarks',
    description_de: 'Längere Dokumente (>21 Seiten) enthalten navigierbare Lesezeichen.',
    level: 'AA',
    wcag_criterion: null,
    bitv_reference: null,
    applies_to: ['pdf', 'document'],
    is_additional: true,
    testing_guidance_de: 'Prüfen Sie das Lesezeichen-Panel in Adobe Acrobat.',
  },
  {
    id: '10.0.4',
    chapter: 10,
    section: '0.4',
    title_de: 'Tabellenstruktur',
    title_en: 'Table Structure',
    description_de: 'Tabellen haben korrekte Kopfzeilen-Tags (TH) und sind nicht für Layoutzwecke verwendet.',
    level: 'A',
    wcag_criterion: null,
    bitv_reference: null,
    applies_to: ['pdf', 'document'],
    is_additional: true,
    testing_guidance_de: 'Prüfen Sie Tabellen-Tags auf TH-Elemente für Kopfzellen.',
  },
  {
    id: '10.0.5',
    chapter: 10,
    section: '0.5',
    title_de: 'Listenstruktur',
    title_en: 'List Structure',
    description_de: 'Listen sind als L/LI-Tags strukturiert, nicht als formatierter Text.',
    level: 'A',
    wcag_criterion: null,
    bitv_reference: null,
    applies_to: ['pdf', 'document'],
    is_additional: true,
    testing_guidance_de: 'Prüfen Sie, ob Aufzählungen als Listen getaggt sind.',
  },
];

// Funktion zum Seeden der Datenbank
export function seedEN301549Criteria(): void {
  const allCriteria = [...CHAPTER_9_CRITERIA, ...CHAPTER_10_CRITERIA];

  const insertStmt = db.prepare(`
    INSERT OR REPLACE INTO en301549_criteria
    (id, chapter, section, title_de, title_en, description_de, level, wcag_criterion, bitv_reference, applies_to, is_additional, testing_guidance_de)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const insertMany = db.transaction((criteria: CriterionSeed[]) => {
    for (const c of criteria) {
      insertStmt.run(
        c.id,
        c.chapter,
        c.section,
        c.title_de,
        c.title_en,
        c.description_de,
        c.level,
        c.wcag_criterion,
        c.bitv_reference,
        JSON.stringify(c.applies_to),
        c.is_additional ? 1 : 0,
        c.testing_guidance_de
      );
    }
  });

  insertMany(allCriteria);
  console.log(`[DB] Seeded ${allCriteria.length} EN 301 549 criteria (Chapter 9: ${CHAPTER_9_CRITERIA.length}, Chapter 10: ${CHAPTER_10_CRITERIA.length})`);
}

// Export für Verwendung im Code
export { CHAPTER_9_CRITERIA, CHAPTER_10_CRITERIA };
